### ISSUE TITLE
Cameras not streaming

### ISSUE THREAD

**Issue by alwaysdesi** [homebridge-simplisafe3/homebridge-simplisafe3#156]
### To Reproduce:
<!— click the video. -->

### Environment:

* **Plugin version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Operating System**: 

### Homebridge Config:

```json
Paste the relevant section of your homebridge config.json here
```

### Logs:

[Link to logs]()
```
Paste Homebridge Logs here
```

**Comment by shamoon** [comment]
Hi @alwaysdesi You did not fill out the template correctly. Please include logs (see instructions in the issue template), your config, etc. so that we can see about helping.

**Comment by alwaysdesi** [comment]
Yeah I’m totally new to this stuff.  And a physician so crazy busy with Covid in the hospital and working overtime.  I had an hour to myself last night so opened up the raspberry pi I bought a month ago and started playing with it.  Will figure out how to get you the proper info as soon as I have a minute free.  
Thanks for your quick reply.

**Comment by shamoon** [comment]
So am I 😀 Most of us do this in our free time...

My guess is it’s going to be something simple but yea whenever you have the chance to provide that stuff we can try to get to the bottom of it.

**Comment by alwaysdesi** [comment]
Holy crap, are you an ED doc in Cali???
I’m a facility Med director/hospitalist at a county hospital in Ohio.

~ Shahrukh Hashmi ~

**Comment by alwaysdesi** [comment]
Are you an ED doc out of Cali?

~ Shahrukh Hashmi ~

**Comment by shamoon** [comment]
Yes though I prefer to keep my personal life a little separate! =)
