### ISSUE TITLE
Sensor refresh received un-expected SSAPI error. Plugins stopped working

### ISSUE THREAD

**Issue by subhro** [homebridge-simplisafe3/homebridge-simplisafe3#157]
### Describe The Bug:
The plugin had been working for the past few months. I noticed that now it does not and the log contains "Sensor refresh received un-expected SSAPI error." once every 15 seconds.

Trying to log into the web interface works, but I noticed that there is a link challenge email sent before the login in allowed now. I believe this is a new step that Simplisafe introduced that caused this problem.

### To Reproduce:
Just install the plugin according to the installation guide.

### Expected behavior:
The plugin is expected to report the current state of the alarm. But it does not.

### Environment:

* **Plugin version**: 1.6.11
* **Node.js Version**: 12.19.0
* **NPM Version**: 6.14.8
* **Homebridge Version**: 1.2.3
* **Operating System**: Raspbian 10

### Homebridge Config:

```json
"platforms": [
        {
            "name": "Homebridge",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "auto",
            "log": {
                "method": "systemd"
            },
            "platform": "config"
        },
        {
            "name": "Home Alarm",
            "auth": {
                "username": "XXXX",
                "password": "XXXX"
            },
            "platform": "homebridge-simplisafe3.SimpliSafe 3"
        }
    ]
```

### Screenshots:

not applicable

### Logs:

[Link to logs]()
```
https://gist.github.com/subhro/7dc3d57f9ba853454589dba87907e766
```

**Comment by shamoon** [comment]
Hi @subhro,

So the "MFA" email system was implemented by SS a while back and this plugin should handle it just fine. If the device homebridge is running on hasn't been 'authorized' yet you should receive a message in the logs to click the email after starting homebridge but only the first time its run. After that (barring any changes to your setup, account changes etc) you shouldn't have to do the MFA thing again for homebridge. And once youre logged in it shouldn't be really related to your issue.

As for your issue, "unexpected SSAPI error"s are common, I get them a lot as my base station occasionally acts up but usually they dont last and usually they dont affect this plugin. Are you seeing this issue persistently i.e. you cannot use the system via HomeKit? Either way, as noted in the issue template, if you would please [enable debug for this plugin](https://github.com/homebridge-simplisafe3/homebridge-simplisafe3#debug) _and_ [for homebridge](https://github.com/homebridge/homebridge/wiki/Basic-Troubleshooting#debug-mode) and post updated logs we can take a look. With debug enabled there should be more information about the error. Without that its tough to say.

**Comment by subhro** [comment]
Hello @shamoon,

Thanks so much for responding. I just restarted the server to enable DEBUG on home bridge, but it looks like restarting the server flushed out the problem and the errors have disappeared as well as the plugin started acting normally again. I am so sorry for the trouble.

Thanks so much.
