### ISSUE TITLE
Homekit Notifications not consistent

### ISSUE THREAD

**Issue by thrangster** [homebridge-simplisafe3/homebridge-simplisafe3#158]
### Describe The Bug:
HomeKit notifications from two SmartLocks is not consistent.. Same notification settings, same lock firmware. Tried multiple iOS and MacOS devices... Sometimes there is a notification, sometimes there is not. 

### To Reproduce:
Activate the lock either manually, via the Simplisafe app, or via HomeKit

### Expected behavior:
Homekit notifies when there is a state change of the lock. 

### Environment:

* **Plugin version**: homebridge-simplisafe3@1.6.11
* **Node.js Version**: v12.18.1
* **NPM Version**: v6.14.5
* **Homebridge Version**: 1.2.3
* **Operating System**: Raspbian

### Homebridge Config:

```
            "name": "Home Alarm",
            "auth": {
                "username": "xxxx",
                "password": "xxxx"
            },
            "cameras": true,
            "debug": true,
            "sensorRefresh": 15,
            "persistAccessories": false,
            "resetSimpliSafeId": false,
            "cameraOptions": {
                "enableHwaccelRpi": false
            },
            "platform": "homebridge-simplisafe3.SimpliSafe 3"
        },
```

### Screenshots:
not applicable

### Logs:
[11/17/2020, 11:20:51] [Home Alarm] Setting target lock state to unlock, 0
[11/17/2020, 11:20:55] [isy-nodejs] Received Heartbeat Signal from ISY: {"seqnum":282,"sid":"uuid:77","control":"_0","action":120,"node":"","eventInfo":""}
[11/17/2020, 11:20:59] [Home Alarm] Alarm received event: DOORLOCK_UNLOCKED
[11/17/2020, 11:20:59] [Home Alarm] Alarm ignoring unhandled event: DOORLOCK_UNLOCKED
[11/17/2020, 11:20:59] [Home Alarm] Basement lock received event: DOORLOCK_UNLOCKED
[11/17/2020, 11:21:06] [Home Alarm] Updated lock state: unlock

[Link to logs]()

```
Paste Homebridge Logs here
```

**Comment by thrangster** [comment]
I dont know what I did wrong

**Comment by shamoon** [comment]
The issue was closed because of formatting issues when you submitted it. No worries. I took a look at this and think I have a fix that should help. Will release soon.

**Comment by shamoon** [comment]
@thrangster Im assuming you restarted homebridge after updating? And please restart your iOS device and HomeKit hub, and perhaps just toggle notifications off and back on. This update made a significant difference for me.

**Comment by thrangster** [comment]
Yes, restarted Homebridge, and did toggle the notifications on and off... will try restarting iOS devices and the HomeKit hub and report back. thanks

**Comment by thrangster** [comment]
Well, I restarted Homebridge a second time, and it seems to be ok now (yes, I know I sound like the idiot user who did NOT restart Homebridge after updating, but I did!) Thanks

**Comment by shamoon** [comment]
No judgements here 😀, glad its improved!
