### ISSUE TITLE
Selectively hide/remove accessories

### ISSUE THREAD

**Issue by caseypugh** [homebridge-simplisafe3/homebridge-simplisafe3#161]
### Is your feature request related to a problem? Please describe:
I manage two homebridge instances, one for my own apartment and one for the entire apartment building I live in. 

Simplisafe is installed for the entire building, and is used in both instances of Homebridge. I do this because I have more complex automations for my own personal setup that controls things happening in my apartment that I dont want my neighbors to see / have access to. However, some of my neighbors have sensors on theirs doors or windows that I do not want to see in my personal homebridge. 

### Describe the solution you'd like:
Would love to specify which devices actually get shown to Homekit users. Either via a allow list or block list. I've seen a similar approach with the Homebridge Harmony and [Wemo](https://github.com/bwp91/homebridge-platform-wemo) plugins

### Describe alternatives you've considered:
Only alternatives I can think of is to create a "Null" room of some sort and bury devices in there, but I really would prefer not to see that my neighbor has opened their window in my own apartment's Homekit and I'm sure my neighbor would prefer that as well.

### Additional context:
Dont have other context to share ATM.

**Comment by shamoon** [comment]
I do see the purpose but sounds like a pretty specific use case and youre the first to ever ask for this. If it gains some traction will consider otherwise cant promise anything. Thanks for input

**Comment by caseypugh** [comment]
I'm the 2nd to request it FWIW https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/issues/79

Thanks for making this plugin, it's great!

**Comment by shamoon** [comment]
Ha, fair enough. Ok will try to get to this soon.

**Comment by shamoon** [comment]
Ok, releasing a new version for this v1.6.13, also a couple fixes to hopefully address your other issue #160

**Comment by caseypugh** [comment]
Amazing, thank you!!
