### ISSUE TITLE
Un-expected SSAPI Error

### ISSUE THREAD

**Issue by sgorman71** [homebridge-simplisafe3/homebridge-simplisafe3#164]
Receiving the following error:
[12/8/2020, 9:21:24 AM] [Home Alarm] Sensor refresh received un-expected SSAPI UnknownError error.
[12/8/2020, 9:21:24 AM] [Home Alarm] {
  type: 'UnknownError',
  message: 'Recieved an Unknown Error: {"type":"Error","message":"invalid wire type 7 at offset 711"}',
  code: '06X',
  statusCode: 500,
  props: {}
}

To Reproduce:, happens during some kind of background refresh if I understand correctly

/homebridge # npm list -g homebridge-simplisafe3
/usr/local/lib
`-- (empty)

/homebridge # node -v
v14.15.1
/homebridge # node -v
v14.15.1
/homebridge # homebridge -V
1.2.4
/homebridge # 

Running in Docker on Synology

### Homebridge Config:
```json
{
    "bridge": {
        "name": "HomebridgeSS",
        "username": "XX:XX:XX:XX:XX:XX",
        "port": 53161,
        "pin": "XX"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8583,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "Home Alarm",
            "auth": {
                "username": "XXX@XXXX.com",
                "password": "XXXXXX"
            },
            "cameras": false,
            "debug": true,
            "sensorRefresh": 15,
            "persistAccessories": true,
            "resetSimpliSafeId": false,
            "cameraOptions": {
                "enableHwaccelRpi": false
            },
            "platform": "homebridge-simplisafe3.SimpliSafe 3"
        }
    ]
}
```

**Comment by sgorman71** [comment]
thanks Bot!

**Comment by shamoon** [comment]
Hi @sgorman71 , please see #163

**Comment by sgorman71** [comment]
Thank you, @shamoon -- I should have searched a bit more thouroughly!
