### ISSUE TITLE
Video feeds not working in Home app

### ISSUE THREAD

**Issue by fhscholl** [homebridge-simplisafe3/homebridge-simplisafe3#165]
### Describe The Bug:
Video feeds are not working in the home app. The cameras activate and shutters open if needed, but only a still image with a loading spinner shows in the app. After about 30 seconds the Home app shows "No Response. The camera is not responding."

Live stream works from the SimpliSafe website and from the SimpliSafe app without issue.

### To Reproduce:
This happens every time I try to access any camera in my home.

### Expected behavior:
A live video feed.

### Environment:

* **Plugin version**: homebridge-simplisafe3@1.6.14
* **Node.js Version**: v14.15.2
* **NPM Version**: 6.14.9
* **Homebridge Version**: 1.1.6
* **Operating System**: Ubuntu 18.04.5 LTS (GNU/Linux 4.15.0-128-generic x86_64)

### Homebridge Config:

```json
        {
            "name": "Home Alarm",
            "auth": {
                "username": "****",
                "password": "****"
            },
            "cameras": true,
            "debug": false,
            "sensorRefresh": 15,
            "persistAccessories": true,
            "resetSimpliSafeId": false,
            "cameraOptions": {
                "enableHwaccelRpi": false
            },
            "platform": "homebridge-simplisafe3.SimpliSafe 3"
        }

```

### Screenshots:
not applicable

### Logs:

[Link to logs](https://gist.github.com/fhscholl/a59c05072cdf27ee838c8aaa833a5e32)

**Comment by shamoon** [comment]
Hmm. Video streaming to HomeKit is a rather mysterious affair and having to stream via SS servers (not e.g. rstp directly from camera) causes a lot of issues with HomeKit "accepting" the feed, unfortunately. Your logs indicate there isnt really anything "wrong" per se, so its likely just that HomeKit wont play it. This can be if latency is high, audio is out of sync, if Mercury is retrograde, etc... Can I ask what kind of home hub are you using? Are you running in Docker or 'bare metal'?

Some things to try include:

- Building your own ffmpeg (a pain often)
- Try lowering resolution to 720p by setting `-vf scale=720:-2`

**Comment by fhscholl** [comment]
I have an Apple TV 4k and a home pod mini. The Homebridge setup is running on bare metal.

I will say when messing with it last night I got it to work exactly one time, but I haven't been able to replicate it since.

i suspect I stumbled upon a different bug with argument parsing. With `"videoOptions": "-vf scale=720:-2"` it seems to break the -2 out as its own parameter:

```
[12/17/2020, 2:47:41 PM] [Home Alarm] /usr/lib/node_modules/homebridge-simplisafe3/node_modules/ffmpeg-for-homebridge/ffmpeg -re -headers Authorization: Bearer LbxHPzLjPx5N6mFB9XupldeP6PWRG0T+oOIT1YkqlrE= -i https://3.210.93.210/v1/a5e6d79de5d5f0aa9609c946203302d5/flv?x=1280&audioEncoding=AAC -map 0:0 -vcodec libx264 -tune zerolatency -preset superfast -pix_fmt yuv420p -r 20 -f rawvideo -vf scale=720: -b:v 284k -bufsize 568k -maxrate 284k -payload_type 99 -ssrc 1735780 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params p5ilHw8+3LJteaxG7tmM2iIwJ9jIFqcJIOJpMPJI srtp://192.168.4.37:58578?rtcpport=58578&localrtcpport=58578&pkt_size=1378 -2  -map 0:1 -acodec libfdk_aac -flags +global_header -profile:a aac_eld -ac 1 -ar 16k -b:a 24k -bufsize 48k -payload_type 110 -ssrc 11500380 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params jxPO5O1i1keJ3j1vZLzoLeyFEqxddYb0dvOi/D/L srtp://192.168.4.37:64671?rtcpport=64671&localrtcpport=64671&pkt_size=188
[12/17/2020, 2:47:41 PM] [Home Alarm] FFMPEG received first frame
[12/17/2020, 2:47:41 PM] [Home Alarm] ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-indev=alsa --enable-outdev=alsa
  libavutil      56. 51.100 / 56. 51.100

[12/17/2020, 2:47:41 PM] [Home Alarm]   libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100

[12/17/2020, 2:47:41 PM] [Home Alarm] Unrecognized option '2'.
Error splitting the argument list: Option not found

[12/17/2020, 2:47:41 PM] [Home Alarm] Error: FFmpeg exited with code 1
```

I'll try a custom build of ffmpeg, but I'm not really sure how that would help.

**Comment by shamoon** [comment]
Ah yea you can use `-vf scale=720:480`. The fact that it does very occasionally work sorta confirms what I was saying about HomeKit being temperamental. I’m not sure building ffmpeg will do anything in that case but can’t hurt to try if scaling down the video doesn’t help

**Comment by fhscholl** [comment]
I did a custom build following https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu with a few tweaks. Same behavior.

Lowering the resolution didn't help either.

Ah well. Thanks for your help.

**Comment by shamoon** [comment]
Bummer. Perhaps lowering the video resolution settings at SS (though I know thats not necessarily “worth it”)? 

Yea sorry I don’t have any great ideas, just lots of trial and error. HomeKit video is very frustrating, it doesn’t give any feedback (ie errors) to help figure out why it won’t stream in a situation like this. FWIW I’ve had it working well on Ubuntu 20 for a while, running in docker.

**Comment by shamoon** [comment]
Ps. Did you try homebridge on another platform just to see if it works there?

**Comment by fhscholl** [comment]
I tried it in docker with the same results, but it is running on the same host. I'll try it on a different machine I have later tonight.
