### ISSUE TITLE
SimpliSafe Down 1/15/2021

### ISSUE THREAD

**Issue by brainstorm-tech** [homebridge-simplisafe3/homebridge-simplisafe3#181]
Good afternoon!  About every other day, I get an "Unknown Error Type" and the SimpliSafe3 plug in stops working.  I can't seem to tell if there is an event triggering it.  A Homebridge restart seems to enable operation for another day or two.  Can you help?

Also, do you accept donations?  Thanks! brainstorm_tech

Homebridge v1.1.7
Homebridge UI v4.36.0
Homebridge Simplisafe3 v1.6.16

1/15/2021, 8:33:55 AM] Homebridge is running on port 51296.
[1/15/2021, 10:39:05 AM] [Home Alarm] Sensor refresh received an error from the SimpliSafe API: "Unknown Error Type": No message provided
[1/15/2021, 10:39:05 AM] [Home Alarm] <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>

[1/15/2021, 10:39:05 AM] [Home Alarm] Sensor refresh received an error from the SimpliSafe API: "Unknown Error Type": No message provided
[1/15/2021, 10:39:05 AM] [Home Alarm] <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>

[1/15/2021, 11:35:09 AM] [Home Alarm] SSAPI socket error: Not authorized

**Comment by shamoon** [comment]
Hi @brainstorm-tech , welcome to GitHub.

Please see #178 #163 #164 #157 (and others, feel free to search)

The majority of these errors come from the pretty unreliable SimpliSafe API. Unfortunately this plugin does not communicate locally with the system (there is no known way for 3rd parties to do that) so we have to rely on their API via the web and it does this. A lot.

That said, the default settings and using the plugin as expected shouldnt cause you to get logged out or your IP blocked. Moreover, the plugin should be able to 'recover' from that in the event it does happen, eventually... So, if none of the above links help we would need more info about how to reproduce, about your setup, etc (mostly the things the issue template asks for =) to look into it more.

**Comment by brainstorm-tech** [comment]
Thanks Michael!

 

I didn’t realize about the template. I started filling it out, then I learned that SimpliSafe’s whole API is broken at the moment.  (I called their tech support.)   So no point in proceeding, at least until they restore basic services.  If the problem persists I will fill out the template.

 

Thank you!

**Comment by shamoon** [comment]
Uh oh. I just noticed that too. Yea, lets see what happens with this drama. I will pin this issue in case others come looking.

Of course SS dont provide any actual status of their API (I guess I could see a security argument for that), but:
https://twitter.com/SimpliSafe/status/1350212355964153856
https://downdetector.com/status/simplisafe/

**Comment by shamoon** [comment]
https://twitter.com/SimpliSafe/status/1350231921192787970?s=20
