### ISSUE TITLE
Homebridge 1.3 (beta 67) reports plugin is slow 

### ISSUE THREAD

**Issue by chris3g** [homebridge-simplisafe3/homebridge-simplisafe3#187]
### Describe The Bug:
Homebridge 1.3.0-beta.67 characteristics warnings feature reports simplisafe3 plugin is slow - 

[2/18/2021, 11:16:21 AM] [homebridge-simplisafe3] This plugin slows down Homebridge. The read handler for the characteristic 'Status Low Battery' was slow to respond! See https://git.io/JtMGR for more info.

### To Reproduce:
Install and configure simplisafe3 plugin on homebridge 1.3

### Expected behavior:
homebridge does not report that plugin is slow

### Environment:

* **Plugin version**: homebridge-simplisafe3 v1.6.16
* **Node.js Version**: v14.15.3
* **NPM Version**: v6.14.9
* **Homebridge Version**: 1.3-beta.67
* **Operating System**: Docker alpine linux 3.12.3

### Homebridge Config:

```json
Paste the relevant section of your homebridge config.json here
```

### Logs:

[Link to logs]()
```
Paste Homebridge Logs here
```

**Comment by shamoon** [comment]
Hi @chris3g , yes Im aware of these as Ive been testing betas for a while. Im going to release 1.16.17 now that should sort these out for the battery status. For other ones I haven't yet decided the best course of action but there are pros/cons to changing everything to work like this.

I'll leave this issue open as we test things, please post back with any relevant updates.

**Comment by chris3g** [comment]
Thanks, i updated to 1.16.17 and as you said it resolved the battery status warning. I'm not currently seeing any other warnings relating to the plugin.
