### ISSUE TITLE
Cannot start the live camera feed

### ISSUE THREAD

**Issue by dallombra** [homebridge-simplisafe3/homebridge-simplisafe3#190]
### Describe The Bug:
Cannot start the camera from within Homekit since upgrading to Homebridge 1.3 - most times the preview updates, but clicking on it to start the live feed always results in a "No response" error

### To Reproduce:
Open Homekit --> tap on preview --> wait for "no response" message

### Expected behavior:
You should be able to view the live feed

### Environment:

* **Plugin version**: homebridge-simplisafe3 v1.6.17
* **Node.js Version**: v14.15.4
* **NPM Version**: v6.14.10
* **Homebridge Version**: 1.3.1
* **Operating System**: Alpine Linux (3.12.3)  - Docker on Synology

### Homebridge Config:
{
            "name": "Home Alarm",
            "auth": {
                "username": "******",
                "password": "*******"
            },
            "cameras": true,
            "sensorRefresh": 15,
            "persistAccessories": true,
            "resetSimpliSafeId": false,
            "cameraOptions": {
                "enableHwaccelRpi": false
            },
            "excludedDevices": [
                "********",
                "********"
            ],
            "platform": "homebridge-simplisafe3.SimpliSafe 3"
        }

### Screenshots:
Not applicable

### Logs:
[Garage] The image snapshot handler for the given accessory is slow to respond! See https://git.io/JtMGR for more info.

**Comment by shamoon** [comment]
Hi @dallombra i would need much more detailed logs than that. Also please enable debug on the plugin before you generate new logs. 

That warning about the snapshots isn’t necessarily the same issue

**Comment by dallombra** [comment]
Of course as soon as I file a bug (and I restart Homebridge for the 100th time)....the camera starts working fine -.-
I guess this can be closed now...
