### ISSUE TITLE
"Unknown Error Type": No message provided showing up over and over

### ISSUE THREAD

**Issue by nebosphere19** [homebridge-simplisafe3/homebridge-simplisafe3#192]
### Describe The Bug:

This shows up over and over again every day, clogging up my log. Would it be possible to suppress them? I realize the issue lies with the Simplisafe API but might it be possible to keep them out of the regular logging?
[Home Alarm] Sensor refresh received an error from the SimpliSafe API: "Unknown Error Type": No message provided

### To Reproduce:

No specific steps. It shows up in the log under normal operation periodically and without any trigger (it seems).

### Expected behavior:

This log entry shouldn't be present.

### Environment:

* **Plugin version**:  1.6.18
* **Node.js Version**: v14.15.4
* **NPM Version**: v7.5.4
* **Homebridge Version**: 1.3.1
* **Operating System**:  MacOS 10.14

### Homebridge Config:

```json
{
    "name": "Home Alarm",
    "auth": {
        "username": "***",
        "password": "***"
    },
    "cameras": true,
    "debug": false,
    "sensorRefresh": 15,
    "persistAccessories": true,
    "resetSimpliSafeId": false,
    "cameraOptions": {
        "enableHwaccelRpi": true
    },
    "platform": "homebridge-simplisafe3.SimpliSafe 3"
}
```

### Screenshots:

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/79610240/109211793-b5856380-777c-11eb-9cc0-d91159861287.png">

### Logs:

[Link to logs]()
```
[2/25/2021, 11:24:46 AM] [Home Alarm] Sensor refresh received an error from the SimpliSafe API: "Unknown Error Type": No message provided
```

Note: I'm unable to get the proper debug logs because another of my devices eats up the entire log space with polling notices (tplink). If I remove that device it removes it from HomeKit and all my automations which I'm not willing to recreate. Hoping the above is enough info or you can help me suppress the tplink debug log entries so I can get you what you need.

**Comment by nebosphere19** [comment]
### Describe The Bug:


This shows up over and over again every day, clogging up my log. Would it be possible to suppress them? I realize the issue lies with the Simplisafe API but might it be possible to keep them out of the regular logging?
[Home Alarm] Sensor refresh received an error from the SimpliSafe API: "Unknown Error Type": No message provided

Note: I'm unable to get the proper debug logs because another of my devices eats up the entire log space with polling notices (tplink). If I remove that device it removes it from HomeKit and all my automations which I'm not willing to recreate. Hoping the above is enough info or you can help me suppress the tplink debug log entries so I can get you what you need.

### To Reproduce:


No specific steps. It shows up in the log under normal operation periodically and without any trigger (it seems).

### Expected behavior:


This log entry shouldn't be present.

### Environment:

* **Plugin version**:  1.6.18
* **Node.js Version**: v14.15.4
* **NPM Version**: v7.5.4
* **Homebridge Version**: 1.3.1
* **Operating System**:  MacOS 10.14

### Homebridge Config:



```json
{
    "name": "Home Alarm",
    "auth": {
        "username": "info@benarons.com",
        "password": "%@byYd#jS0pLjRGB"
    },
    "cameras": true,
    "debug": false,
    "sensorRefresh": 15,
    "persistAccessories": true,
    "resetSimpliSafeId": false,
    "cameraOptions": {
        "enableHwaccelRpi": true
    },
    "platform": "homebridge-simplisafe3.SimpliSafe 3"
}
```

### Screenshots:

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/79610240/109211793-b5856380-777c-11eb-9cc0-d91159861287.png">
### Logs:





[Link to logs]()
```
[2/25/2021, 11:24:46 AM] [Home Alarm] Sensor refresh received an error from the SimpliSafe API: "Unknown Error Type": No message provided
```

**Comment by shamoon** [comment]
Hey @nebosphere19 FYI your username/pw was included above. Please change it ASAP.

As for the issue, I agree theyre annoying and have been worse lately. I chose to show them because it "explains" to users when sometimes something doesnt work, like "it's the API" so Im a little on the fence about totally suppressing them but I will think about how to make less... annoying.

**Comment by shamoon** [comment]
@nebosphere19 please try the latest version, should be much quieter =)

**Comment by nebosphere19** [comment]
Thanks so much! 

I’m going to change my password now. I can’t believe I mistakenly put that up there 🤦🏼‍♂️

Can you please delete the other closed issue requests I created? At least one is still showing the username/password combo.

Much appreciated.

Ben

**Comment by shamoon** [comment]
I think only @nzapponi can delete issues, looks like you already edited them at least... (#193 #194)

**Comment by nebosphere19** [comment]
Turns out it’s still happening and now it’s showing a bunch of markup in the error as well. Using the latest version. 
[homebridge.log.txt](https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/files/6053728/homebridge.log.txt)

**Comment by shamoon** [comment]
Is that with debug _disabled_? I think you may also need to clear your cached accessories too. That can affect HomeKit automations though so you may want to be careful. Config UI X let’s you delete them one-by-one

and you weren’t kidding about the tplink logs

**Comment by nebosphere19** [comment]
There is definitely an earlier part of the log with debug enabled. Have a
look at just 2/26/21 late afternoon on and later.....

**Comment by shamoon** [comment]
You need to disable debug on the plug-in (config.js) and for homebridge (`-D`). If you have debugging disabled you shouldn’t see the actual error content at all

**Comment by nebosphere19** [comment]
Ah! My mistake. Thanks for pointing that out.
