### ISSUE TITLE
Home app accessories all show No Response

### ISSUE THREAD

**Issue by thrangster** [homebridge-simplisafe3/homebridge-simplisafe3#208]
### Expected behavior:

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Operating System**: 

### Logs:
<nothing in logs regarding Simplisafe - debug is turned on -->
[Link to logs]()
```
Paste Homebridge Logs here
```

**Comment by shamoon** [comment]
There is no information provided here. No Response almost always indicates an issue in your setup somewhere (there are tons of places online to look, just google that error you’ll see). If you can actually identify an issue with this plug-in we can readdress.

**Comment by thrangster** [comment]
Thanks - it seemed self resolve after about 2 hours.... (other Homebridge plug ins were working fine)

The log thing is very confusing to a non-technical person. I looked in the logs in the HB web  gui, but there was nothing about the Simplisafe plug-in - plenty of other log info...

Anyway, thanks for getting back

**Comment by thrangster** [comment]
I pasted all the other info inside the brackets, not sure why it didn't appear - sorry
