### ISSUE TITLE
Error when launching the camera view

### ISSUE THREAD

**Issue by dallombra** [homebridge-simplisafe3/homebridge-simplisafe3#209]
Hi, I do have one Simplicam in my setup. The preview works and updates correctly, but as soon as I tap the preview to launch the live feed, nothing happens and when I check the logs I can see the following error

![image](https://user-images.githubusercontent.com/8121975/114045694-1de95980-9880-11eb-9a92-11ef9faeb814.png)

Anyone knows what this is and how to solve this?

Everything else in the plugin  works great and it's generally amazing!

**Comment by shamoon** [comment]
Hi @dallombra . As the bot suggested, some basic info is missing here like your OS, versions etc. but that error `spawn unknown system error -8` sounds like something about your setup.
