### ISSUE TITLE
Simplicam Live Stream Doesn’t Work

### ISSUE THREAD

**Issue by dallombra** [homebridge-simplisafe3/homebridge-simplisafe3#210]
### Describe The Bug:
When clicking on the camera preview to launch the live stream, nothing happens and I get a Node error in the logs (see below). On the same HomeKit setup I have a nest video doorbell which works ok.

### To Reproduce:
Click on the camera preview from HomeKit app

### Expected behavior:
I would expect the live stream to start.

### Environment:

* **Plugin version**: homebridge-simplisafe3 v1.6.19
* **Node.js Version**: v14.16.0
* **NPM Version**: v6.14.11
* **Homebridge Version**: v1.3.4
* **Operating System**: Synology NAS - Docker - Alpine Linux (3.12.4)

### Homebridge Config:

```json
{
            "name": "Home Alarm",
            "auth": {
                "username": "***@******",
                "password": "*******"
            },
            "cameras": true,
            "sensorRefresh": 15,
            "persistAccessories": true,
            "resetSimpliSafeId": false,
            "cameraOptions": {
                "enableHwaccelRpi": false
            },
            "excludedDevices": [
                "******",
                "******"
            ],
            "platform": "homebridge-simplisafe3.SimpliSafe 3"
        }
```

### Screenshots:
![52F2B659-F4D6-466F-ACD5-3BEF56D05935](https://user-images.githubusercontent.com/8121975/114143856-9138ad00-990c-11eb-881b-e7a0ba296c56.jpeg)

### Logs:

**Comment by shamoon** [comment]
I have a feeling this has to do with your environment since thats what I see when Googling the issue a bit. Not sure if its something about how Synology handles Docker, something to do with Node, etc. Thing is, I dont have any of that stuff to test (or even know how they really work) and things work fine in other environments, of course. But there are other people using Synology successfully so maybe its something to do with settings there...

**Comment by dallombra** [comment]
Thanks for the feedback. Are there additional logs I should provide, or other places I should post to try and find a solution to this?

**Comment by dallombra** [comment]
Small feedback: I believe this issue is generated by my firewall probably blocking the port(s) needed by the plugin to communicate with the camera live feed. Is there a list of ports that I need to whitelist?

**Comment by shamoon** [comment]
To the WAN it should only be using 80/443. It uses other ports on the local
network, but which ones it binds is determined at runtime

**Comment by dallombra** [comment]
Thanks for the help, I think I’m getting there. Manually forwarding those got rid of the error I was seeing above, but still the livestream doesn’t start.
The only thing showing up in the logs is this

![085C85D2-F1D8-43E0-A139-33B8718BDDFF](https://user-images.githubusercontent.com/8121975/114304885-77929380-9acd-11eb-918b-7c899d41d411.jpeg)

**Comment by shamoon** [comment]
That message is for snapshots. Please enable debug (see readme) and try again and you can post the log, there will be lots of output

**Comment by dallombra** [comment]
Hi, thanks for the help so far. Please see attached a copy of the logs I see when I start the live stream. All seems ok, I can't see any obvious errors, but still no live stream starts
[Simplicam Logs.txt](https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/files/6295964/Simplicam.Logs.txt)

**Comment by shamoon** [comment]
Hmm, as you said, the logs look fine, looks like the plug-in is doing it’s job so seems like an issue outside this plug-in. For example, wondering if this is a networking issue with your your device communicating with your hub.

**Comment by dallombra** [comment]
Thanks for the confirmation, I suspect as well there is still something wrong with my network configuration, but so far I haven’t managed to find a decent solution.

I guess this ticket can be closed as nothing is wrong with the plugin!

Again, many thanks for the help!

**Comment by shamoon** [comment]
If you figure it out please post back, may help someone figure out something similar!
