### ISSUE TITLE
Entry sensors not updating

### ISSUE THREAD

**Issue by lucanaut** [homebridge-simplisafe3/homebridge-simplisafe3#217]
I've noticed lately that the entry sensors (doors, windows) aren't updating in Homekit.  Not sure what it could be do to.  Any way to diagnose what the issue might be?  All I can think of is a recent software update from SimpliSafe...

**Comment by shamoon** [comment]
Hi @lucanaut , Im not seeing this. I have automations that depend on entry sensors (e.g. windows open turn off AC) and they are working OK, see screenshot. As the issue template states, sometimes config, logs etc. might be helpful if you think there's a bug. And in general restarting things can often help!

<img width="538" alt="Screen Shot 2021-06-01 at 10 39 13 AM" src="https://user-images.githubusercontent.com/4887959/120367473-c38bd880-c2c5-11eb-93ed-9c0474a1a053.png">

**Comment by lucanaut** [comment]
I admit I am pretty new at the whole reporting issues thing so I need to look into the template and how to do that properly!  Thank you
