### ISSUE TITLE
no matching subscription

### ISSUE THREAD

**Issue by cruzalinson** [homebridge-simplisafe3/homebridge-simplisafe3#225]
i have the standard tier for simplisafe that works with homeassistant but is not actively working with hoobs 

![image](https://user-images.githubusercontent.com/62040002/128379915-bbcaccd9-141e-49bc-abaa-cf8263217e22.png)
my subscription does support the api otherwise it would not work on HA

**Comment by shamoon** [comment]
Hi @cruzalinson , please update the issue with all of the info requested in the template and I can take a look. Thanks
