### ISSUE TITLE
Mic/ two way audio support?

### ISSUE THREAD

**Issue by Flaming-Gamer101** [homebridge-simplisafe3/homebridge-simplisafe3#230]
### Is your feature request related to a problem? Please describe:
I don't exactly have a problem but would just like to use the mic/two way audio on my simplicam and doorbell.

### Describe the solution you'd like: 
I would like to be able to use the mic to speak to people and pets via the camera.

### Describe alternatives you've considered:
I have used the simplisafe app for this feature but it just sucks and is very slow to load even with 500 mbps internet it also logs me out and goes down freuquently.

**Comment by Flaming-Gamer101** [comment]
What do you mean I literally used the template to make it

**Comment by shamoon** [comment]
Heh, yea the bot can be... aggressive. You need to include every piece of the template.

Anyway, this would be great I agree but its a non-starter as its not supported by the SimpliSafe API AFAIK. So even if we could tackle the not-insignificant technical hurdles we dont even have a way to send the audio to SS. Bummer, I agree.

**Comment by Flaming-Gamer101** [comment]
Oh wow that's sad
