### ISSUE TITLE
Warning: Authentication with username / password is expected to cease to function on or after December 2021. Please re-authenticate using newest method. See README for more info.

### ISSUE THREAD

**Issue by jussin5150** [homebridge-simplisafe3/homebridge-simplisafe3#247]
### Describe The Bug:
I upgraded to HOOBS 4 and the plugin no longer works. The 

### To Reproduce:
Installing the plugin doesn't ask for authentication, login, or password

### Expected behavior:
I would like to 

### Environment:

* **Plugin version**: 1.8.4
* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Operating System**: Raspbian

### Homebridge Config:

```json
Paste the relevant section of your homebridge config.json here
```

### Screenshots:
![image](https://user-images.githubusercontent.com/69946053/136704278-44ef82bb-c410-4a8a-bc7e-bbd4d9b7bcb4.png)

![image](https://user-images.githubusercontent.com/69946053/136704280-9e5333da-6002-4c36-822c-0d9a79311e33.png)

### Logs:

[Link to logs]()
```
Paste Homebridge Logs here
10/10/2021, 11:03:35 AMSimplisafe3 BridgeLoaded plugin 'homebridge-simplisafe3'
10/10/2021, 11:03:35 AMSimplisafe3 BridgeLoading 1 platforms...
10/10/2021, 11:03:35 AMSimplisafe3 BridgeHome AlarmSpecifying account number: 00169889
10/10/2021, 11:03:35 AMSimplisafe3 BridgeHome AlarmWARNINGWarning: Authentication with username / password is expected to cease to function on or after December 2021. Please re-authenticate using newest method. See README for more info.
10/10/2021, 11:03:35 AMSimplisafe3 BridgeHome AlarmAttempting to login with username / password.
10/10/2021, 11:03:35 AMSimplisafe3 BridgeHome AlarmFound 0 cached accessories being configured
10/10/2021, 11:03:36 AMSimplisafe3 BridgeBridge is running on port 51876.
10/10/2021, 11:03:36 AMSimplisafe3 BridgeHome AlarmUsername / password login failed.
10/10/2021, 11:03:36 AMSimplisafe3 BridgeHome AlarmERRORSee the plugin README for more information on authenticating with SimpliSafe.
10/10/2021, 11:03:36 AMSimplisafe3 BridgeHome AlarmERRORInitial accessories refresh failed with error: Error: Not authenticated with SimpliSafe.
    at /var/lib/hoobs/simplisafe3bridge/node_modules/homebridge-simplisafe3/index.js:103:56
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
10/10/2021, 11:10:14 AMRoomba Stv BridgeRoombaBattery status requested
10/10/2021, 11:10:14 AMRoomba Stv BridgeRoombaRunning status requested

<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->

**Comment by shamoon** [comment]
Hi @jussin5150 , this plugin does not explicitly support HOOBS, it is built with homebridge. From your screenshots it looks like HOOBS doesnt show the button(s) to authenticate with the new method which means you will have to use the command line tool. As for username / password, that should be in your config.

Please see the [readme for relevant info](https://github.com/homebridge-simplisafe3/homebridge-simplisafe3#simplisafe-authentication), let us know if youre still having trouble.

**Comment by jussin5150** [comment]
I'm not sure how to use the command line tool. Can you help me with that?

Justin

**Comment by shamoon** [comment]
Please see the link I posted, the readme. Perhaps you can reach out to HOOBS if you need help? Or you can always switch to homebridge =)
