### ISSUE TITLE
Certified for hoobds but doesnt work.

### ISSUE THREAD

**Issue by Gitmoslave** [homebridge-simplisafe3/homebridge-simplisafe3#250]
### Describe The Bug:

Listed as a certified plugin for hoobs, however the install/config page has no instructions, and seemingly no way to authenticate.  the support page offers instructions for homebridge, which is not hoobs.  If this is certified for hoobs (which it says it is), where can i find the step by step, non-programmer level instructions on how to make this work so i can integrate simplisafe with homekit?
### To Reproduce:

Install
### Expected behavior:

I expect the config page would have what is needed to config the product
### Environment:
Hoobs- Latest version
Your product, latest version in hoobs certified plugins 
* **Plugin version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**: 
* **Operating System**: 

### Homebridge Config:

```json
Paste the relevant section of your homebridge config.json here
```

### Logs:

[Link to logs]()

Paste Homebridge Logs here
```

<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -->

**Comment by Gitmoslave** [comment]
What a joke.

**Comment by shamoon** [comment]
Hi, yes the bot is aggressive. Please search first, there have been a few threads for this recently. See #247, #248 and #249 in particular see https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/issues/249#issuecomment-945154711
