### ISSUE TITLE
Set a characteristic when API authentication fails

### ISSUE THREAD

**Issue by shaungrady** [homebridge-simplisafe3/homebridge-simplisafe3#264]
### Is your feature request related to a problem? Please describe:

It seems as if the auth token occasionally expires, or otherwise becomes invalid for me, and I don't realize it until I try to disarm the system through HomeKit and end up triggering an alarm when I open a door. Combined with another issue—albeit unrelated—I had a false alarm this morning, which is never fun.

### Describe the solution you'd like:

It would be nice to have a characteristic set that I can use as part of an automation to notify me of the auth failure. Maybe [HMCharacteristicTypeObstructionDetected](https://developer.apple.com/documentation/homekit/hmcharacteristictypeobstructiondetected), or even a custom characteristic?

### Describe alternatives you've considered:

Can't think of another way inside of the HomeKit context.

**Comment by shamoon** [comment]
Hey @shaungrady , while I appreciate your end goal what you’re describing is kinda unorthodox in the HomeKit landscape. In particular, that attribute wouldn’t work since no SS devices use it (they’re not garage doors).

Do you have any insight into why authentication is failing? Ie logs that might be helpful? The last user who reported this had an issue with another plug-in. It has been quite solid for me (and most others, I believe) which is why I ask.

TBH I keep most manufacturer apps on my phone just in case (eg my smart garage door, ecobee, SS, etc) in case HK bails

**Comment by shaungrady** [comment]
I'm not so sure it's _completely_ unorthodox; for example, here's a screenshot of my Ecobee thermostat characteristics:

<img width="588" alt="image" src="https://user-images.githubusercontent.com/52413/144761993-30b6a82a-0f71-45fc-bc04-acc4f90841d7.png">

They decided to use the very descriptive name of "Custom," but non-standard characteristics are effectively ignored and not exposed by the Home app, but third party apps like Controller allow you to see them and create automations based on their state.

Here's another example from my VOCOlinc power strip:

<img width="575" alt="image" src="https://user-images.githubusercontent.com/52413/144762209-55e4a685-382e-48a7-ba6a-c8726e450e5e.png">

Characteristic request aside, I'm not sure why it's failing. I've enabled debug logs, and I'll try to diagnose it the next time it fails. I'm running the `oznu/homebridge` docker image, so it's nothing exotic.

I also keep the manufacturer apps on my phone, but I'm just looking to add an automation that sends me a push notification when auth fails, so I don't get woken up by my alarm siren again 😉

**Comment by shamoon** [comment]
Closed in https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/commit/a4a2a7f44c61918555c3990fb38f1133ad85a96f

**Comment by shamoon** [comment]
Hey @shaungrady I implemented this in 1.8.5 with the 'General Fault' property, hopefully thats useful

**Comment by shaungrady** [comment]
Awesome, thank you!
