### ISSUE TITLE
Link Account

### ISSUE THREAD

**Issue by toops2014** [homebridge-simplisafe3/homebridge-simplisafe3#271]
### Describe The Bug:
When I initially go to setup the plugin and click on "Link Account" under configuration a blank white box comes up 
<img width="1280" alt="Screen Shot 2021-12-31 at 5 23 56 PM" src="https://user-images.githubusercontent.com/5104576/147840230-17c63689-6b6c-4f4f-a38f-6c86961c196f.png">

### To Reproduce:
Initially set up plugin and click link account

### Expected behavior:
according to the instructions it should com up with a screen to login to simplisafe

### Environment:

* **Plugin version**:  1.88
* **Node.js Version**: 4.0.42
* **NPM Version**: 
* **Homebridge Version**: 4.1.20
* **Operating System**: macOS

**Comment by shamoon** [comment]
Hi @toops2014 im not aware of any issues like this. Looks like you are using HOOBS which is not affiliated with this plug-in directly. You may want to reach out to them.
