### ISSUE TITLE
Problem w/ motion sensor automation

### ISSUE THREAD

**Issue by betabob** [homebridge-simplisafe3/homebridge-simplisafe3#297]
Hi there - I had a motion sensor automation setup on the Home app which was working fine until I just upgraded to the latest version of your plug in...at which point it stopped working. Is this a known issue? If not, is there any info I can provide to assist you with identifying the cause of the issue? Thanks!

Bob

**Comment by shamoon** [comment]
Hi @betabob , no there is not a known issue but of course is possible. As the bot said, please use the issue template and fill out the required items, it includes a lot of information that would be useful in trying to help.
