### ISSUE TITLE
Unable to authenticate using new authentication method in Safari 15.4 Beta

### ISSUE THREAD

**Issue by jaromirrivera** [homebridge-simplisafe3/homebridge-simplisafe3#304]
### Describe The Bug:
Unable to authenticate using new authentication method. You are not able to get the redirected URL from the javascript console (non-safari browsers) or from Safari.

### To Reproduce:
Initiate the login process in the plugin settings or command line.

### Expected behavior:
Retrieve the Redirected URL to paste into the settings for the plugin.

### Environment:

* **Plugin version**: 1.9.4
* **Node.js Version**: v16.14.0
* **NPM Version**: v8.3.1
* **Homebridge Version**: v1.4.0

* **Operating System**: 

### Screenshots:
"not applicable"

### Logs:

[Link to logs]()
```
[2/20/2022, 4:11:24 PM] [Home Alarm] SimpliSafe login failed with error: Error: Failed refreshing token: Error: Request failed with status code 403
    at SimpliSafe3AuthenticationManager.refreshCredentials (/homebridge/node_modules/homebridge-simplisafe3/lib/authManager.js:238:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by shamoon** [comment]
Hi @jaromirrivera Are you saying youre not able to get the plugin to authenticate at all using the new method? If so, you need to give much more explicit description, perhaps even including screenshots. This is confirmed to be working for most people so if theres an issue it'll have to be ferreted out.

**Comment by jaromirrivera** [comment]
Hi, yes when you try to authenticate via the new method. You get presented to the SimpliSafe login page, you successfully login but no longer get a Redirected URL… seems that SimpliSafe has modified their login process or checks and is no longer replying back with the com.simplisafe.mobile:// URL…

**Comment by jaromirrivera** [comment]
![4A43248C-BFC2-4927-ABED-BF055C9EDF7B](https://user-images.githubusercontent.com/878904/154867847-727a187c-c343-44e6-b0b7-0bfe76ca113b.jpeg)

**Comment by shamoon** [comment]
I am able to perform the login currently so I dont think things have changed.

That error is what youre supposed to see, but only after you've logged in. The address bar should show `com.simplisafe.mobile://...` and that is the URL you need.

What version of Safari are you using? Perhaps in older versions it doesnt even change the address bar? In that case again I'd guess its in the error console. You can also try Chrome incognito (where, again, you will have to look in the error console).

Here's a screenshot from Safari 15.2, as you see theres an error but thats OK, we just want the URL.

<img width="750" alt="Screen Shot 2022-02-20 at 2 51 28 PM" src="https://user-images.githubusercontent.com/4887959/154867971-cb526816-75b6-4512-ac90-ba95c9f0f678.png">

**Comment by jaromirrivera** [comment]
I’m on Safari 15.4, the address bar nor the Console shows the URL now…

**Comment by jaromirrivera** [comment]
I was able to test this out in a VM with Safari 15.2 and confirmed your findings and I get the same error page but with the Redirected URL on the page and in the address bar... so it looks to be like some changes to Safari 15.4 and security settings that may need to be accounted for in the future with 15.4 is rolled out to wider audience...

**Comment by shamoon** [comment]
Well I dont have the beta version of the browser installed, but sounds like the solution will have to be: "use another browser" =)

I can test when the time comes, suppose it might change before then.
