### ISSUE TITLE
Stop removing cached accessories when API login token fails

### ISSUE THREAD

**Issue by elcid2012** [homebridge-simplisafe3/homebridge-simplisafe3#305]
### Is your feature request related to a problem? Please describe:
For the last three months, every 30 days my Simplisafe login token expires. The plugin doesn't seem to be able to keep it alive. When authentication fails, all cached accessories are deleted from HomeKit instead of being marked as "Not Responding" like other plugins do when they cannot reach a device. This removes these accessories from scenes and automations requiring me to completely re-do all of this work every month.

### Describe the solution you'd like:
Stop removing accessories when the API token expires.

### Describe alternatives you've considered:
I guess actually setup the messaging system letting me know there's an issue with authentication and requires manual intervention every 30 days. Although, it appears the plugin works correctly right up until the moment the token expires, so this notification system won't prevent cached accessories from getting deleted.

### Additional context:
N/A

**Comment by shamoon** [comment]
Hi @elcid2012 . A couple things about this dont make sense:

- Sounds like you should check [`Persist Accessories`](https://github.com/homebridge-simplisafe3/homebridge-simplisafe3#persistaccessories)
- Even if the above is not checked (which it should be), accessories wouldn't be removed until the next time you restart Homebridge. When authentication fails it would trigger your failure message (the point of that `Status Fault` feature), and nothing would change immediately (though yes 'No Response'). If you re-authenticate before restarting there shouldn't be a problem.
- There is no time limit on authentication, theoretically it should be able to continue forever. Clearly, that doesnt happen, but it shouldn't literally be "every 30 days". It is actually re-authenticating approximately every hour along the way.

If something above is not working as expected perhaps theres an issue.

**Comment by elcid2012** [comment]
Thanks for pointing out “Persist Accessories” which is unchecked. I will monitor it from here. I’ve had to reauthenticate manually on 18 Dec, 17 Jan, and again just today (stopped working at some point but I’ve been too busy with a PhD program lately to catch exactly when it happened most recently). I’ve been writing down the dates and monitoring it for the last three months before submitting a ticket to make sure I’m not crazy.

I see in the logs the authentication attempts which are successful for the most part unless SimpliSafe API is sucking. I’ve also tried not checking the “Remember this device for 30 days” option as well as checking it when authenticating. It does not make a difference.

Hopefully this persist accessories option will fix stuff getting deleted. The 30 day expiration might be out of your control. I’ll set up the messaging system soon to notify me when it’s failing. If you have any other ideas, I’m happy to take them. Thanks again.

**Comment by shamoon** [comment]
- I think setting up an automation to let you know when auth fails https://github.com/homebridge-simplisafe3/homebridge-simplisafe3#authentication-failure-notifications
- Interesting about 30 days, not how I thought it works: ["[refresh tokens] essentially allow a user to remain authenticated forever."](https://auth0.com/docs/secure/tokens/refresh-tokens) but I could be wrong.
- Yea, API crapping out is an issue, handling that crappiness is forever a work-in-progress for the plugin, obviously we cant control it but preventing it handling it as gracefully as possible...
