### ISSUE TITLE
Not recognizing monitoring plan

### ISSUE THREAD

**Issue by bigchrisatx** [homebridge-simplisafe3/homebridge-simplisafe3#321]
### Describe The Bug:
When I add credentials to access my SimpliSafe account is says I don't have a matching plan and I have the Self Monitoring plan.
![image](https://user-images.githubusercontent.com/47667537/157786084-70a4ed90-01b4-4655-9cdc-dd83a7eeb77b.png)

### To Reproduce:
Restart Homebridge, error happens in log.

### Expected behavior:
The Plugin sees my account has a plan associated with it and allows me to use my SS devices with the bridge

### Environment:

* **Plugin version**: 9.1.10
* **Node.js Version**: v16.14.0
* **NPM Version**: 
* **Homebridge Version**: 1.4.0
* **Operating System**: Ubuntu 

### Homebridge Config:
{
    "bridge": {
        "name": "Homebridge BA29",
        "username": "0E:44:23:D6:BA:29",
        "port": 53303,
        "pin": "031-45-154"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "Home Alarm",
            "cameras": true,
            "subscriptionId": "395923",
            "sensorRefresh": 15,
            "persistAccessories": true,
            "resetSimpliSafeId": false,
            "cameraOptions": {
                "enableHwaccelRpi": false
            },
            "platform": "homebridge-simplisafe3.SimpliSafe 3"
        }
    ]
}

### Screenshots:
Not Applicable

### Logs:

[Link to logs]()
```
[homebridge.log.txt](https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/files/8228350/homebridge.log.txt)


```

**Comment by shamoon** [comment]
Hey @bigchrisatx , from your logs it looks like youre not running the newest version, is that intentional?
`[3/10/2022, 7:43:46 PM] Loaded plugin: homebridge-simplisafe3@1.9.3`

Newest version is 1.9.10, perhaps reinstall?

**Comment by shamoon** [comment]
What happens if you remove the account number from your config?

**Comment by bigchrisatx** [comment]
Account number removed, same result.

![image](https://user-images.githubusercontent.com/47667537/157961496-c19df8fa-0fb5-4fdb-9d7f-fc04343ee2ef.png)

**Comment by shamoon** [comment]
Would you feel comfortable editing the code a little to tell me what happens? Specifically, add `this.log(data);` to line 259 of `simplisafe.js` and restart then send output please.

Thanks

**Comment by bigchrisatx** [comment]
I added "this.log(data);" to the following location on the .js file.
![image](https://user-images.githubusercontent.com/47667537/157977942-5014e541-7d1b-448b-986a-d000639a4878.png)

Attached is the log out put after restarting.
[homebridge.log.txt](https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/files/8236029/homebridge.log.txt)

**Comment by shamoon** [comment]
Sorry thats not the right spot. You should be editing the file in `.../node_modules/homebridge-simplisafe3/simplisafe.js` (the location of your node_modules depends on your install process). Here's a screenshot of those lines so you can see

<img width="694" alt="Screen Shot 2022-03-11 at 2 13 42 PM" src="https://user-images.githubusercontent.com/4887959/157979280-ff574be7-2a1e-4b94-9af5-50dab1a12e18.png">

**Comment by bigchrisatx** [comment]
Here is the output:
subscriptions: [
    {
      uid: 4709237,
      sid: 5034415,
      sStatus: 7,
      activated: 0,
      planSku: 'SSSLFCAM',
      planName: 'Self Monitoring with Camera Recording',
      price: 9.99,
      currency: 'USD',
      country: 'US',
      expires: 1649589716,
      canceled: 0,
      extraTime: 0,
      creditCard: [Object],
      time: 2628000,
      paymentProfileId: '2153105216',
      upgradeStatus: 0,
      features: [Object],
      status: [Object],
      subscriptionFeatures: [Object],
      dispatcher: 'cops',
      dcid: 0,
      activationCode: '',
      systemVersion: 20,
      orderProductId: 0,
      location: [Object],
      pinUnlocked: true,
      pinUnlockedBy: 'pin',
      billDate: 1649589716,
      billInterval: 2628000,
      autoActivation: null
    }

**Comment by shamoon** [comment]
I think I see the issue. BTW, I suspect that your account number is wrong and if you put in the right one it would work, but still this seems like the plugin should handle this better. I'll release a fix in a few, please tell me if it works for you.

Thanks for your patience

**Comment by bigchrisatx** [comment]
That worked, thanks!
