### ISSUE TITLE
Sensor Refresh Errors Every 30 Seconds or So

### ISSUE THREAD

**Issue by kapblam** [homebridge-simplisafe3/homebridge-simplisafe3#325]
Hi there,

Running homebridge-simplisafe3 v1.9.11 in your Docker mode, I get the following error in the log every 30 seconds or so. Anyone else seeing this or did I mess something up?

```
[3/13/2022, 3:58:29 PM] [Home Alarm] Sensor refresh received an error from the SimpliSafe API: {
  type: 'SettingsInProgress',
  message: 'The Settings Requested are already being modified and cannot be accessed at this time',
  code: '200',
  statusCode: 409,
  props: {}
}
```

**Comment by shamoon** [comment]
Hi, these errors are common and can safely be ignored when things are working, it’s not the plug-in per se it’s the SS API failing to reach the base station. Disabling `debug` would make these less noisy.

**Comment by kapblam** [comment]
Good to know - thanks for the quick response. Great support!
