### ISSUE TITLE
Unable to Authenticate

### ISSUE THREAD

**Issue by jlyfshhh** [homebridge-simplisafe3/homebridge-simplisafe3#326]
### Describe The Bug:
When attempting to authenticate, the page does not load as expected. I have tried Safari and Chrome

### To Reproduce:
Click "LAUNCH SIMPLISAFE LOGIN" from the Homebridge UI.

### Expected behavior:
The page should load the proper URL to authenticate

### Environment:

* **Plugin version**:  v1.9.11
* **Node.js Version**: v16.13.2
* **NPM Version**: v8.1.2
* **Homebridge Version**: v1.4.0
* **Operating System**: macOS 12.3 beta

### Homebridge Config:
{
            "name": "Home Alarm",
            "cameras": false,
            "sensorRefresh": 15,
            "persistAccessories": true,
            "resetSimpliSafeId": false,
            "cameraOptions": {
                "enableHwaccelRpi": false
            },
            "platform": "homebridge-simplisafe3.SimpliSafe 3",
            "_bridge": {
                "username": "username",
                "port": 38265
            }

### Screenshots:
<img width="1743" alt="image" src="https://user-images.githubusercontent.com/57607562/158094022-e5ad9de9-4093-429a-91c4-1ff5c21660ab.png">

### Logs:
[3/13/2022, 10:10:33 PM] [Homebridge UI] [homebridge-simplisafe3] Incoming Request: /getAuthCodeFromUrl
[3/13/2022, 10:17:45 PM] [Homebridge UI] [homebridge-simplisafe3] Terminating child process...
[3/13/2022, 10:17:45 PM] [Homebridge UI] [homebridge-simplisafe3] Child process ended
[3/13/2022, 10:21:53 PM] [Homebridge UI] [homebridge-simplisafe3] Incoming Request: /credentialsExist
[3/13/2022, 10:21:53 PM] [Homebridge UI] [homebridge-simplisafe3] Incoming Request: /getCodeVerifier
[3/13/2022, 10:21:53 PM] [Homebridge UI] [homebridge-simplisafe3] Incoming Request: /getSSAuthURL
[3/13/2022, 10:22:02 PM] [Homebridge UI] [homebridge-simplisafe3] Terminating child process...
[3/13/2022, 10:22:02 PM] [Homebridge UI] [homebridge-simplisafe3] Child process ended

**Comment by shamoon** [comment]
Sorry I cannot confirm this, it works fine. I have to guess something is off in how you are doing it, though of course may be a bug I cant reproduce.

Does it ever work? What does browser error console show?  Can you copy + paste your full URL here please.

**Comment by jlyfshhh** [comment]
Here is the URL I get:

https://auth.simplisafe.com/continue?state=hKFo2SBWYXpqTnV2ZFFES1BCNUM2Y0liWTZaQ3RES0doWVl5MqFuqHJlZGlyZWN0o3RpZNkgZXJCeXhkMC10R3l4N1FBb28tc1NBcmpPYjh1YUc1b0SjY2lk2SA0MmFCWjVsWXJWVzEyamZPdXUzQ1FST2l0d3hnOXNONQ

<img width="1743" alt="image" src="https://user-images.githubusercontent.com/57607562/158095291-00921879-5a2e-447c-a898-0ff928115186.png">

**Comment by shamoon** [comment]
That is not the first URL you get from the plugin. Can you login to SS at all right now?

**Comment by jlyfshhh** [comment]
Yes I can login to my account on the site just fine. The initial URL that it goes to once I click the button in homebridge is:

https://tsv.prd.platform.simplisafe.com/v1/tsv/check?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNhdWRpbGxAcHJvdG9ubWFpbC5jb20iLCJvb2JfY29kZSI6IjM0YWM0NWFkYThjYjQ5ZGE4YTU4NTkzM2I3ZjU4N2U2IiwiaWF0IjoxNjQ3MjI1OTE2LCJleHAiOjE2NDcyMjY4MTYsImF1ZCI6Imh0dHBzOi8vdHN2LnBsYXRmb3JtLnNpbXBsaXNhZmUuY29tLyIsImlzcyI6Imh0dHBzOi8vYXV0aC5zaW1wbGlzYWZlLmNvbS8iLCJzdWIiOiJhdXRoMHxzcy11c2Vyc3wyMjQ5NzU4IiwianRpIjoiMjcwYTlmZmViZjA3NDYzMTkwMTFmMzViNTA5MjUyZGEifQ.eisttYPlcnsQ-wf4oKmRHuJkatMjuWPry-TO_vZfUyk&state=hKFo2SB6d19GbWh0WVVhMk5Cb3NINGNWY2ZPaGNPZEp2TkdtTaFuqHJlZGlyZWN0o3RpZNkgVmNLREU3S193SkZWUlpFWUFrWjNDWm55SmxUS2oxZW2jY2lk2SA0MmFCWjVsWXJWVzEyamZPdXUzQ1FST2l0d3hnOXNONQ

**Comment by shamoon** [comment]
Sorry, when you click the "Launch" link from the settings, right-click and copy that address =)

**Comment by jlyfshhh** [comment]
https://auth.simplisafe.com/u/login?state=hKFo2SAtM3g4eTJkOTVPb2loeU8xR3NNajBFd3FfUjA4clZheqFur3VuaXZlcnNhbC1sb2dpbqN0aWTZIFhFbDhOR25YamN1Z0FaVXFfRmhMSV91U0FDRlo3R0U4o2NpZNkgNDJhQlo1bFlyVlcxMmpmT3V1M0NRUk9pdHd4ZzlzTjU

**Comment by shamoon** [comment]
The URL from the settings should look like:

https://auth.simplisafe.com/authorize?client_id=42aBZ5lYrVW12jfOuu3CQROitwxg9sN5&scope=offline_access%20email%20openid%20https://api.simplisafe.com/scopes/user:platform&response_type=code&redirect_uri=com.simplisafe.mobile%3A%2F%2Fauth.simplisafe.com%2Fios%2Fcom.simplisafe.mobile%2Fcallback&code_challenge_method=S256&code_challenge=***&audience=https://api.simplisafe.com/&auth0Client=eyJuYW1lIjoiQXV0aDAuc3dpZnQiLCJlbnYiOnsiaU9TIjoiMTUuMCIsInN3aWZ0IjoiNS54In0sInZlcnNpb24iOiIxLjMzLjAifQ

**Comment by Homekitdude** [comment]
All of my Frame TVs stopped working. Simply nothing works with this plugin anymore, bummed.

**Comment by jlyfshhh** [comment]
Just tried this again on my Mac mini with Safari, Chrome, and Firefox. Also on my iPad without the Simplisafe app installed and on a fresh Windows 11 VM with Microsoft Edge. I get the same URL each time and the plugin does not accept it. Not sure what to do at this point.

**Comment by shamoon** [comment]
When you right click the login button in the plugin and copy that link, what does it give you? It should look like my comment above

**Comment by jlyfshhh** [comment]
Right clicking on the button and copying the link gives me this just like yours. At this point, I am thinking it's something with my Eero network and Secure that's messing with the redirect and since it's not an issue with the plugin I am gonna close this. Thanks for your help.

https://auth.simplisafe.com/authorize?client_id=42aBZ5lYrVW12jfOuu3CQROitwxg9sN5&scope=offline_access%20email%20openid%20https://api.simplisafe.com/scopes/user:platform&response_type=code&redirect_uri=com.simplisafe.mobile%3A%2F%2Fauth.simplisafe.com%2Fios%2Fcom.simplisafe.mobile%2Fcallback&code_challenge_method=S256&code_challenge=r-YkK-ho872_zmyKLCNdeARVdkZAcVpYCPT-qaqlySw&audience=https://api.simplisafe.com/&auth0Client=eyJuYW1lIjoiQXV0aDAuc3dpZnQiLCJlbnYiOnsiaU9TIjoiMTUuMCIsInN3aWZ0IjoiNS54In0sInZlcnNpb24iOiIxLjMzLjAifQ
