### ISSUE TITLE
Camera doesn't stream

### ISSUE THREAD

**Issue by jtsshieh** [homebridge-simplisafe3/homebridge-simplisafe3#327]
### Describe The Bug:
When opening a camera stream, it loads for a long time until it finally says "Not Responding". 

### To Reproduce:
Add a camera (I've tried Indoor Cam and Doorbell) and start streaming on the Apple Home app.

### Expected behavior:
The camera streams as it would in the SimpliSafe app.

### Environment:

* **Plugin version**: 1.9.11
* **Node.js Version**: 16.14.0
* **NPM Version**:  8.5.1
* **Homebridge Version**: 1.4.0
* **Operating System**: Raspbian Homebridge Image

### Homebridge Config:
```json
{
    "name": "Home Alarm",
    "cameras": true,
    "debug": true,
    "sensorRefresh": 15,
    "persistAccessories": true,
    "cameraOptions": {
        "enableHwaccelRpi": true
    },
    "platform": "homebridge-simplisafe3.SimpliSafe 3",
    "_bridge": {
        "username": "xxxxxxxxxx",
        "port": xxxxxxxx
    }
}
```

### Screenshots:
not applicable

### Logs:
[Link to logs](https://gist.github.com/jtsshieh/52437bceb87fe79c3fa0bfa4d03cb947)

**Comment by jtsshieh** [comment]
I've checked out issue #238 already however, they get a "MMAL" related error, while I get absolutely nothing.

**Comment by shamoon** [comment]
This will probably be an ffmpeg issue. Please post all of your logs, not just a snippet

**Comment by shamoon** [comment]
Also what Pi are you using?

**Comment by jtsshieh** [comment]
The end of the gist is the end of the logs while it is buffering.

When the "No Response" shows up, I only get
```json
[19/03/2022, 16:56:43] [Home Alarm] handleStreamRequest with request: { sessionID: '68592d5b-f494-4b2f-ae8d-25b6c8913598', type: 'stop' }
[19/03/2022, 16:56:43] [Home Alarm] Camera stopped streaming
[19/03/2022, 16:56:56] [Home Alarm] SSAPI socket `heartbeat`
```

in addition to that..

I am using a Raspberry Pi 3 Model B.

**Comment by shamoon** [comment]
Yea, 3b has been reported to not really work, see https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/issues/147 , https://github.com/homebridge-simplisafe3/homebridge-simplisafe3#known-issues

Sorry Im not really sure what else I can do for that one. There are some ideas you can try in the thread.

**Comment by jtsshieh** [comment]
Okay thanks for the help anyways!
