### ISSUE TITLE
Signal handling error when trying to install

### ISSUE THREAD

**Issue by Tiger519** [homebridge-simplisafe3/homebridge-simplisafe3#328]
### Describe The Bug:
I'm trying to install via Config UI X. It seems to install successfully, but then fails when it terminates the process (which ends up causing the plugin to not be installed). Not sure if this is an issue with homebridge-simplisafe3 or another module. Here is the log up from the "install Completed" message through the error.

1055 timing command:install Completed in 449527ms  
1056 verbose stack Error: process terminated  
1056 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:197:39  
1056 verbose stack     at process.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/signal-handling.js:51:5)  
1056 verbose stack     at process.emit (node:events:532:35)
1057 verbose cwd /usr/local
1058 verbose Linux 5.10.92+
1059 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge-simplisafe3@latest"
1060 verbose node v16.14.0
1061 verbose npm  v8.5.1
1062 error process terminated
1063 error signal SIGTERM
1064 verbose exit 1
1065 timing npm Completed in 455948ms
1066 verbose unfinished npm timer reify 1647970569300
1067 verbose code 1

### To Reproduce:
Try to install through Config UI X

### Expected behavior:
It installs

### Environment:
Plugin version: 1.9.11
Node.js Version: 16.14.0
NPM Version: 8.5.1
Homebridge Version: 1.4.0
Operating System: Raspbian Homebridge Image

**Comment by shamoon** [comment]
I do not think this has to do with the plugin, I think something is up with your npm or node or what Im not really sure tbh. Can you install any plugins?

**Comment by Tiger519** [comment]
I believe you are correct, I just tried to install another plugin and got the same error. Looking at issues on the homebridge repo it appears to be an issue with homebridge itself and Node.js 16.x. Will try downgrading to Node.js 14.x, though I am curious if anyone has gotten this to work with 16. Regardless, I'm going ahead and closing the issue.
