### ISSUE TITLE
[BUG] Streaming video error

### ISSUE THREAD

**Issue by jasworks** [homebridge-simplisafe3/homebridge-simplisafe3#333]
### Description

When streaming video I got a message:

```
[4/9/2022, 10:32:32 PM] [Simplisafe] Unable to spawn ffmpeg process at undefined with error: TypeError: The "file” argument must be of type string. Received undefined:
new NodeError (node: internal/errors:371:5) at
validateString (node: internal/validators:120:11)
normalizeSpawnArguments (node:child process:505:3)
spawn (node:child process:693:13) at
StreamingDelegate.handleStreamRequest(/usr/lib/nodemodules/homebridge-simplisafe3/lit/streamingDelegate.js:372:48)
code:
'ERR INVALID ARG TYPE’

```
Sorry for the bad copy & paste as it is really hard to do it in iPad.

I have this video encoding setting which worked before:

-vcodec h264_v4l2m2m

### Expected behavior

Streaming should work.

### Steps to reproduce

1. Start video streaming in Home App.
2. Check the Homebridge log.

### Homebridge logs

```bash
[4/9/2022, 10:32:32 PM] [Simplisafe] Unable to spawn ffmpeg process at undefined with error: TypeError: The "file” argument must be of type string. Received undefined:
new NodeError (node: internal/errors:371:5) at
validateString (node: internal/validators:120:11)
normalizeSpawnArguments (node:child process:505:3)
spawn (node:child process:693:13) at
StreamingDelegate.handleStreamRequest(/usr/lib/nodemodules/homebridge-simplisafe3/lit/streamingDelegate.js:372:48)
code:
'ERR INVALID ARG TYPE’
```

### Homebridge config.json contents

```json
n/a
```

### Plugin version

latest

### Homebridge version

latest

### Node.js version

latest

### Host OS

Ubuntu

**Comment by shamoon** [comment]
Same as https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/issues/332 I would guess that ffmpeg is not installed. Please try reinstalling things and/ or verifying the install

**Comment by shamoon** [comment]
Hey, can you update to v1.10.3, I believe that will fix this issue, one of the plugin dependencies had a bug in it.

**Comment by jasworks** [comment]
It is working now once I upgraded. Thanks.
