### ISSUE TITLE
SS Added reCAPTCHA

### ISSUE THREAD

**Issue by shamoon** [homebridge-simplisafe3/homebridge-simplisafe3#352]
### Discussed in https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/discussions/351

It looks like SS have added reCAPTCHA breaking the login process. No ETA on the fix yet but will likely mean we have to revert to a more manual approach

<div type='discussions-op-text'>

<sup>Originally posted by **FL350** July 21, 2022</sup>
Hi  - I haven't been able to auth. I've tried both using the UI and manually via terminal but get the same error below:

> [21/07/2022, 17:51:45] Homebridge v1.5.0 (HAP v0.10.2) (Homebridge 2A1C) is running on port 51719.
> [21/07/2022, 17:52:18] [Homebridge UI] [homebridge-simplisafe3] Incoming Request: /credentialsExist
> [21/07/2022, 17:52:18] [Homebridge UI] [homebridge-simplisafe3] Incoming Request: /nLoginSteps
> [21/07/2022, 17:52:53] [Homebridge UI] [homebridge-simplisafe3] Incoming Request: /initiateLoginAndAuth
> [21/07/2022, 17:52:53] [Homebridge UI] [homebridge-simplisafe3] Loading login auth url...
> [21/07/2022, 17:52:54] [Homebridge UI] [homebridge-simplisafe3] Attempting to login with credentials...
> [21/07/2022, 17:52:54] [Homebridge UI] [homebridge-simplisafe3] Authentication error: Request failed with status code 400
> [21/07/2022, 17:52:59] [Homebridge UI] [homebridge-simplisafe3] Terminating child process...
> [21/07/2022, 17:52:59] [Homebridge UI] [homebridge-simplisafe3] Child process ended

I don't see anything in the README or in discussions. For reference, I am using it on Pi running Adguard and the install seems to have gone to /home/homebridge. Not sure what's going on. 
</div>

**Comment by bachya** [comment]
As discussed, Python folks are tracking this, too: https://github.com/bachya/simplisafe-python/issues/370
