### ISSUE TITLE
[BUG] last update authentication fail after some time

### ISSUE THREAD

**Issue by jdmtv001** [homebridge-simplisafe3/homebridge-simplisafe3#355]
### Description

I've been using the plugin for a while and works well for the most part. yesterday I updated the plugin to the latest version. I had to authenticate again. I've done so, rebooted homebridge and everything was working. However, I see that after a few hours, not sure how many the plugin is no longer authenticated and I need to do it again. I need to repeat the authentication process every few hours for this to work. 

### Expected behavior

Once authenticated should remain authenticated.

### Steps to reproduce

Authenticate then verify status every hour. Not sure how long it actually takes for this to happen.

### Homebridge logs

```bash
7/24/2022, 5:33:59 PM] [Home Alarm] {
  message: 'Request failed with status code 400',
  name: 'Error',
  description: undefined,
  number: undefined,
  fileName: undefined,
  lineNumber: undefined,
  columnNumber: undefined,
  stack: 'Error: Request failed with status code 400\n' +
    '    at createError (/volume1/homebridge/node_modules/homebridge-simplisafe3/node_modules/axios/lib/core/createError.js:16:15)\n' +
    '    at settle (/volume1/homebridge/node_modules/homebridge-simplisafe3/node_modules/axios/lib/core/settle.js:17:12)\n' +
    '    at IncomingMessage.handleStreamEnd (/volume1/homebridge/node_modules/homebridge-simplisafe3/node_modules/axios/lib/adapters/http.js:322:11)\n' +
    '    at IncomingMessage.emit (node:events:539:35)\n' +
    '    at endReadableNT (node:internal/streams/readable:1345:12)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:83:21)',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      Host: 'auth.simplisafe.com',
      'Content-Length': 186,
      'Auth0-Client': 'removed for this post',
      'User-Agent': 'axios/0.26.1'
    },
    baseURL: 'https://auth.simplisafe.com/oauth',
    method: 'post',
    url: '/token',
    data: '{"grant_type":"refresh_token","client_id":"removed for this post ","refresh_token":"token removed for this post}',
    'axios-retry': { retryCount: 0, lastRequestTime: 1658702039128 }
  },
  code: undefined,
  status: 400
```

### Homebridge config.json contents

```json
,
        {
            "name": "Home Alarm",
            "cameras": true,
            "sensorRefresh": 15,
            "persistAccessories": true,
            "cameraOptions": {
                "enableHwaccelRpi": false
            },
            "_bridge": {
                "username": "xxxxxxxxxxx",  replced the original username for this post
                "port": 39789
            },
            "platform": "homebridge-simplisafe3.SimpliSafe 3"
```

### Plugin version

homebridge-simplisafe3 v1.10.7

### Homebridge version

1.5.0

### Node.js version

v16.16.0

### Host OS

Debian

**Comment by shamoon** [comment]
Yea, Im working on tracking this down. Thanks for your patience.

**Comment by idealdreams** [comment]
I'm experiencing the exact same behavior. Updated the plugin yesterday due to the API change on SimpliSafe's end and after a few hours, the authentication is lost and the plugin begins to error out until Homebridge restarts and the Home app accessories are unresponsive.

**Comment by betabob** [comment]
I'm also experiencing the same issue and can provide more info, if necessary.

**Comment by shamoon** [comment]
Hi all, please give 1.10.8 a try and let me know if youre still having issues. The issue seemed to occur on [occasional] refreshing credentials, so yea not immediately.

**Comment by shaungrady** [comment]
Been stable for for five days now, I think it's OK to call this bug crushed. Thanks for the quick response. 🙇

**Comment by stephaniemfong** [comment]
Wanted to add onto this -- I had the same issue and after updating to 1.10.8, the issue seemed fix but it seems a day or two ago the issue has recurred. Reauthenticated again just now, so we'll see how long this holds.

**Comment by idealdreams** [comment]
The same issue began with me today on the latest release as well. It was fine until now following the current update which fixed it initially.

**Comment by kakiser56** [comment]
Rebooting no longer solves the issue. I tried a few times but alas, no luck.
