### ISSUE TITLE
[BUG] General Fault not being triggered on deauthentication

### ISSUE THREAD

**Issue by shaungrady** [homebridge-simplisafe3/homebridge-simplisafe3#361]
### Description

Related to [this issue](https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/issues/264) and [this commit](https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/commit/a4a2a7f44c61918555c3990fb38f1133ad85a96f) to set the accessory to a fault state when deauthenticated, this functionality is no longer working. The last time it was known to work for me was before changes were made to [address this issue](https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/issues/355).

### Expected behavior

When the plugin becomes deauthenticated, the fault flag should be set to true on the accessory.

### Steps to reproduce

- Invalidate the authentication token
- Check the fault flag on the accessory

### Homebridge logs

```bash
[8/12/2022, 9:30:59 PM] [Home Alarm] SimpliSafe login failed with error: {
  message: 'Request failed with status code 400',
  name: 'Error',
  description: undefined,
  number: undefined,
  fileName: undefined,
  lineNumber: undefined,
  columnNumber: undefined,
  stack: 'Error: Request failed with status code 400\n' +
    '    at createError (/homebridge/node_modules/homebridge-simplisafe3/node_modules/axios/lib/core/createError.js:16:15)\n' +
    '    at settle (/homebridge/node_modules/homebridge-simplisafe3/node_modules/axios/lib/core/settle.js:17:12)\n' +
    '    at IncomingMessage.handleStreamEnd (/homebridge/node_modules/homebridge-simplisafe3/node_modules/axios/lib/adapters/http.js:322:11)\n' +
    '    at IncomingMessage.emit (node:events:539:35)\n' +
    '    at endReadableNT (node:internal/streams/readable:1345:12)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:83:21)',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      Host: 'auth.simplisafe.com',
      'Auth0-Client': '<redacted>',
      'User-Agent': 'axios/0.26.1',
      'Content-Length': 77
    },
    baseURL: 'https://auth.simplisafe.com/oauth',
    method: 'post',
    url: '/token',
    data: '{"grant_type":"refresh_token","client_id":"<redacted>"}',
    'axios-retry': { retryCount: 0, lastRequestTime: 1660365058849 }
  },
  code: undefined,
  status: 400
}
[8/12/2022, 9:30:59 PM] [Home Alarm] See the plugin README for more information on authenticating with SimpliSafe.
[8/12/2022, 9:30:59 PM] [Home Alarm] Initial accessories refresh failed with error: Error: Not authenticated with SimpliSafe.
    at /homebridge/node_modules/homebridge-simplisafe3/index.js:101:56
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Homebridge config.json contents

```json
n/a
```

### Screenshots

<img width="305" alt="image" src="https://user-images.githubusercontent.com/52413/184502712-d30e6c57-142f-4e0b-9322-b25c34a30d14.png">

### Plugin version

v1.10.8

### Homebridge version

v1.5.0

### Node.js version

v16.16.0

### Host OS

Docker

**Comment by shamoon** [comment]
Do you mean on startup or during operation?

**Comment by shaungrady** [comment]
Both. The fault wasn't triggered on the accessory when my token expired. I restarted HomeBridge, and it wasn't triggered after restarting, either.

**Comment by shamoon** [comment]
I've been testing a v1.10.9 beta which seems to handle this better. Im testing a couple more things and also will hopefully be reverting back to "automatic auth" so this wont be released immediately. Feel free to test the beta but usual warnings about beta software apply.
