### ISSUE TITLE
[BUG] 400: Bad Request Error

### ISSUE THREAD

**Issue by nickcurmi** [homebridge-simplisafe3/homebridge-simplisafe3#362]
### Description

Logs are showing a 400: Bad request error when Homebridge attempts to communicate with SimpliSafe.

### Expected behavior

When an attempt is made at changing the status of the alarm via homebridge, the logs return a 400: Bad Request error. When the alarm state is changed by the keypad, no communication shows in the logs whatsoever.

### Steps to reproduce

1) attempt to change status of alarm in homebridge. 2) View errors in logs. 3) Attempt (successfully) to change status of alarm via keypad. 4) view lack of communication in logs 

### Homebridge logs

```bash
See attached image. Can’t seem to copy from the web browser on my phone currently and computer is dead.
```

### Homebridge config.json contents

```json
The json is virtually all personal information. The config is managed by the UI/X plug-in, so I’d doubt anything is wrong with the config.
```

### Screenshots

![2B0C5397-1ECF-41C1-B080-9E33E1161668](https://user-images.githubusercontent.com/97310227/184509279-50400894-f398-41d4-a9d6-59d0cd599a02.jpeg)

### Plugin version

V1.10.8

### Homebridge version

1.5.0

### Node.js version

16.14.0

### Host OS

Raspbian

**Comment by shamoon** [comment]
I cannot reproduce this issue. Have you tried simple things like restarting and re-authenticating?

**Comment by jandagroup** [comment]
I can also confirm this same bug resulting in a 400 error on every request made via HomeKit/Homebridge. I’m using the latest beta and have restarted Homebridge and have re-authenticated with SS. 

I may try deleting the plugin and reinstalling to see if that fixes the issue. 

I’ll report back if I’m successful.

**Comment by shamoon** [comment]
Honestly, I dont think theres a real bug here, I think more likely is that authentication needed to be re-done. But if anyone thinks theres a real bug it would be helpful to see full logs, not just a screenshot of one error, but logs from homebridge startup all the way through to the error.

**Comment by nickcurmi** [comment]
Hi @shamoon, I thought the same thing at first too. I’ve re-authenticated several times already. Just tried again just now. Still having the same issues. Been using this plugin for quite some time and never had an issue - this is the first time I’ve seen an error.

the difficulty with the logs is all the personal information in them. Let me see if I can scrub those and attach what isn’t personal here. I’ll get back to you shortly.

**Comment by nickcurmi** [comment]
@shamoon Here are the logs with my personal information pulled out:

[scrubbedhomebridge.log.pdf](https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/files/9332672/scrubbedhomebridge.log.pdf)

**Comment by shamoon** [comment]
Thank you but that looks like the same error repeated over and over, which doesnt help much unfortunately. Specifically:

- Clear the logs
- Enable debug
- Re-authenticate
- Restart
- Send **full** (including all the stuff at the beginning) logs up through when you try to change the alarm state and presumably get the error. I only need to see it once, this should be like one minute of running the plugin after restart and trying to do something.

Most of the content is not actually sensitive but feel free to redact things if youre not sure. Also, you can put the logs into comment here or http://pastebin.com, or even just .log file no pdf needed =)

**Comment by nickcurmi** [comment]
@shamoon so really strange behavior this time. I lost the accessory that control the home alarm after restart. It was there for a few seconds after restart and then was removed. I looked in advanced settings and it said the “persist old accessories” checkbox was set to false. I did not change that to false though.

I can’t test the behavior after clearing the logs/reauthenticating without that accessory. Unfortunately, I can’t seem to figure out how to get it back.

many thoughts on what else I can try?

**Comment by shamoon** [comment]
> many thoughts on what else I can try?

The logs will probably explain what happened / is happening, for example if authentication had been lost (as I wondered initially) and then you restart without re-authenticating first and "Persist accessories" isn't checked the accessories will be removed.

The "nuclear" option is to remove all cached accessories and remove the plug-in and reinstall, but again I'd guess the logs will shed some light.

**Comment by kakiser56** [comment]
Same thing is happening to me. I tried to re-authenticate, but I am never given the correct URL (using Firefox) to get the token.

**Comment by nickcurmi** [comment]
@shamoon So I ended up uninstalling and reinstalling the plugin. When I did that, it said I was already authenticated in the authentication window. But then I looked at the logs and it is definitely an authentication error. Every time I re do it I get a success screen in the simply safe UI. But apparently something is broken in the back end. 

As soon as I get back to a computer tonight, I’ll scrub the logs and resend.

**Comment by shamoon** [comment]
You are restarting after you successfully re-authenticate? Yes clean logs as described above might be helpful if something is going haywire.

Also SS sometimes blocks IPs that are hitting the API too often so you could also try turning it off for a night completely if you're still having issues.

**Comment by nickcurmi** [comment]
@shamoon I am wondering if I found the source of the problem. The authentication instructions say the URL should begin with com.SimpliSafe.mobile://. However, the URLs that I'm getting all start with https://tsv.prd.platform.simplisafe.com/. Could SS have changed their URL structure which could be leading to the problem? Every time I try to paste the URL I get in it keeps saying Error Retrieving Token, please try again.

**Comment by shamoon** [comment]
So

1. Please read the instructions again, the URL is shown in the Javascript console not the URL bar, and Chrome seems to work best. See this discussion for more: https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/discussions/359
2. I previously spent ages figuring out how to get "automatic" login to work and then SS went and added ReCAPTCHA to the login page (#352) which completely broke things. Good news is they seem to have removed it and I am planning on re-releasing the automatic login soon. I hope that reduces the difficulty for folks.

**Comment by nickcurmi** [comment]
@shamoon I was trying the developer console last last night when I read that. I keep getting nothing showing up in console when I try that. I'm using Chrome on a Mac Book Pro. 

Here is a screenshot. 
<img width="1668" alt="Screen Shot 2022-08-15 at 7 21 39 AM" src="https://user-images.githubusercontent.com/97310227/184653671-5759b72e-0028-42ae-98ea-476905cff82b.png">

**Comment by shamoon** [comment]
Yea something’s off there. If you look at the screenshots in the post I linked to that final page should show “redirecting…” (which it never does but that’s what gets the URL to show in the console. Ensure you are using the login link directly from the plug-in.

Anyway, I just released 1.10.9 which adds back the more automatic login, hopefully that will sort things out. Fingers crossed SS don’t break it again soon, they implemented ReCAPTCHA (which broke login for us) for like 3 weeks and suddenly removed it so who knows…

**Comment by nickcurmi** [comment]
@shamoon thank you for updating! 

I just updated the plug-in and re-authenticated using credentials. It was successful. Then I restarted homebridge.

The weird thing is that the accessories didn’t show back up in homebridge. The config now has the SimpliSafe info in there again now that I’ve reauthenticated but can’t seem to get the accessories back.

Any thoughts on what else I can try.

**Comment by nickcurmi** [comment]
@shamoon just kidding - seems to have worked! I uninstalled and reinstalled the plugin. Then re-authenticated and it loses the accessories!

thanjs so much for your help!
