### ISSUE TITLE
[BUG] Unable to maintain auth with SS as of 4/5/23

### ISSUE THREAD

**Issue by shamoon** [homebridge-simplisafe3/homebridge-simplisafe3#386]
### Description

No longer able to obtain refresh tokens, see https://github.com/bachya/simplisafe-python/issues/487

### Expected behavior

Auth

### Steps to reproduce

1. Authenticate plugin

### Homebridge logs

```bash
n/a
```

### Homebridge config.json contents

```json
n/a
```

### Plugin version

v1.10.12

### Homebridge version

v1.6.0

### Node.js version

any

### Host OS

Docker

**Comment by jasworks** [comment]
I can confirm that this is happening. Seems like a major issue that all server calls result in 400 error. I can attach logs if needed.

**Comment by shamoon** [comment]
Yes, Im aware of it which is why I opened the issue. SS have changed the way the API works and we now have to try and reverse-engineer.

**Comment by jasworks** [comment]
Thanks. I also posted to SimpliSafe forums in multiple posts as a complaint to them. Lack of HomeKit automation is a no go for a good tech oriented security system. Sent from my iPhoneOn 5 Apr 2023, at 22:55, shamoon ***@***.***> wrote:﻿
Yes, Im aware of it which is why I opened the issue. SS have changed the way the API works and we now have to try and reverse-engineer.

**Comment by shamoon** [comment]
Yea it's very frustrating, I sincerely doubt any help from them, they've never been interested or in the least supportive. Do let me know if you hear anything...

**Comment by infamous-pattern** [comment]
Seeing the same thing. Hopefully it can be fixed. Thanks.

**Comment by kbanning** [comment]
I'm facing the same issue.  I was receiving 403 but re-authing with the browser and javascript console link copying now gets me a status 400 error. Busted.

**Comment by shamoon** [comment]
Yes, literally everyone using this plug-in has or is about to run into this.

Trialing a fix atm…

**Comment by kdorepos** [comment]
Updated to the 1.10.13 release and am still receiving the 400 errors. I restarted Homebridge after the update. Should I look at redoing auth?

```
[4/5/2023, 11:09:19 PM] [Security System] Error while setting alarm state: Error: 400: Bad Request
    at SimpliSafe3.request (/homebridge/node_modules/homebridge-simplisafe3/simplisafe.js:211:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at SimpliSafe3.getUserId (/homebridge/node_modules/homebridge-simplisafe3/simplisafe.js:252:16)
    at SimpliSafe3.getSubscriptions (/homebridge/node_modules/homebridge-simplisafe3/simplisafe.js:261:18)
    at SimpliSafe3.getSubscription (/homebridge/node_modules/homebridge-simplisafe3/simplisafe.js:289:18)
    at SimpliSafe3.setAlarmState (/homebridge/node_modules/homebridge-simplisafe3/simplisafe.js:346:7)
    at SS3Alarm.setTargetState (/homebridge/node_modules/homebridge-simplisafe3/accessories/alarm.js:140:18)
```

**Comment by shamoon** [comment]
Yes, you will need to re-authenticate, I should have noted that.

I cant say it's been tested long-term but hopefully v1.10.13 should get folks back up and running. A consequence of the change SS made is that we are now at their mercy in terms of how frequent we will have to re-login. It's not clear what they have that set to (30 days — 1 year) but it should mimic the mobile app which anecdotally I don't think logs me out every 30 days.

For now this is as good as we can do.

**Comment by kdorepos** [comment]
Cool cool, sounds good. Thanks @shamoon!

**Comment by kdorepos** [comment]
FYI - when I go ahead and put in the new `com.simplisafe.com` URL, you do seem to get an initial set of errors. Saving and restarting Homebridge does get you going again, but some people might get deterred by those initial errors.

**Comment by kbanning** [comment]
1.10.13 and a re-auth fixed the issue here. **Thanks so much for the fast and fresh fix shamoon!**  I did have to re-enter my SystemID because I have multiple accounts but I encountered no other problems or errors.

**Comment by brainstorm-tech** [comment]
Yes thanks!  Going to try it soon as I can!Sent from my iPhoneOn Apr 5, 2023, at 9:22 PM, Keith Banning ***@***.***> wrote:﻿
1.10.13 and a re-auth fixed the issue here. Thanks so much for the fast and fresh fix shamoon!  I did have to re-enter my SystemID because I have multiple accounts but I encountered no other problems or errors.

**Comment by pjgolian** [comment]
This is not working for me.  When I click the "Launch SimpliSafe Login" button and after signing in, I get a blank page.  Tried in both Edge and Chrome and had the same result.

**Comment by ibmaster** [comment]
Worked for me. Had to update plug-in, restart, reauth process, and restart again. Thanks!Ben.Sent from my iPhoneOn Apr 5, 2023, at 9:47 PM, pjgolian ***@***.***> wrote:﻿
This is not working for me.  When I click the "Launch SimpliSafe Login" button and after signing in, I get a blank page.  Tried in both Edge and Chrome and had the same result.

**Comment by mpc12pats** [comment]
I can confirm this new version also works for me with the same flow....upgrade, restart, authenticate, restart.

However one thing I've noticed since getting this working again, I'm not getting real time notifications anymore. For example, prior, I'd get an iOS notification every time my front door was opened (door sensor). I can see all my sensors in the logs so I know it knows about them, but no notifications are coming through. I've double checked all the settings, toggled notifications off then back on again, no impact. Anyone else seeing this behavior? 

**shamoon** - Thank you for the quick fix!!!

**Comment by iartemiev** [comment]
Thank you so much for the super fast turnaround on this!

**Comment by nickcurmi** [comment]
@shamoon thanks so much for building the fix for this so quickly!

I am having new issues with reauthentication. When I click on the authenticate button in the config UI/X, all I get is a blank screen. The url it sends me to begins with auth.SimpliSafe.com/u/MFA-detect-browser

I’m using chrome on a MacBook to run the authentication, which has worked in the past.

many ideas?

**Comment by infamous-pattern** [comment]
> @shamoon thanks so much for building the fix for this so quickly!
> 
> I am having new issues with reauthentication. When I click on the authenticate button in the config UI/X, all I get is a blank screen. The url it sends me to begins with auth.SimpliSafe.com/u/MFA-detect-browser
> 
> I’m using chrome on a MacBook to run the authentication, which has worked in the past.
> 
> Any ideas?

Yeah, I was going to report the same thing.

**Comment by nickcurmi** [comment]
@shamoon you’re right, I was already logged in! Weird because I did t authenticate, but skipping forward to looking at Dev Console got me the com.SimpliSafe url to paste in. Maybe it cached my login from a few months ago somehow? Either way, it’s working again. Thanks for your help!

**Comment by infamous-pattern** [comment]
> You're already logged in, if there isn't a URL at the bottom already try in private mode, or logout

Yup, my bad. I've got it working again. Thanks for the help!

**Comment by brainstorm-tech** [comment]
Authentication worked perfectly – thanks Shamoon!

 

 

From: Ed Christians ***@***.***>
Date: Wednesday, April 5, 2023 at 9:26 PM
To: homebridge-simplisafe3/homebridge-simplisafe3 ***@***.***>
Cc: homebridge-simplisafe3/homebridge-simplisafe3 ***@***.***>, Subscribed ***@***.***>
Subject: Re: [homebridge-simplisafe3/homebridge-simplisafe3] [BUG] Unable to maintain auth with SS as of 4/5/23 (Issue #386)

 

Yes thanks!  Going to try it soon as I can!

Sent from my iPhone




On Apr 5, 2023, at 9:22 PM, Keith Banning ***@***.***> wrote:

﻿

1.10.13 and a re-auth fixed the issue here. Thanks so much for the fast and fresh fix shamoon! I did have to re-enter my SystemID because I have multiple accounts but I encountered no other problems or errors.

**Comment by chiachs** [comment]
Hi all, fairly new at this homebridge thing but I went through all the instruction on this thread and still cannot get it to work. I am copying the link but when restarting still get errors in the logs. I can send logs if needed just not sure if I should be sharing them through here.

**Comment by thetaz001** [comment]
First off, THANK YOU to the developers for amazing fast response to the latest change by SS, and quickly working to get it intrgrated , that is amazing! and super apprecaited!
I am having issues getting this to re-auth..
I attempted to re-auth as suggested above, but when i attempt the re-auth, i never get presented the link with the simplisafe.mobile link.
i deleted the plug in, and attempted to re-configure from scratch, and still no good, even though i deleted the plug in, it still said auth has already been setup..
but i cant get it to auth properly.

**Comment by chiachs** [comment]
> Hi all, fairly new at this homebridge thing but I went through all the instruction on this thread and still cannot get it to work. I am copying the link but when restarting still get errors in the logs. I can send logs if needed just not sure if I should be sharing them through here.

I was finally able to get it to work. My bad I was copying the whole line starting at com.simplisafe , when I should have only copied starting from mfa.

thanks

**Comment by nickcurmi** [comment]
Is anyone else having an issue with SimpliSafe status triggering automations? Ever since the update, when I arm SimpliSafe I get the “Arming…” text underneath while it is arming but then when it arms it still says “Arming…”. If I click on the tile, it shows away/home though. I have several automations that trigger on arm/disarm and none are firing. Seems to have started since the fix went into place. I also tried deleting and recreating the automations and same behavior is happening.

Anyone else having the same error? Any troubleshooting tips/advice?

**Comment by Githubnewbynewb** [comment]
> Yes, you will need to re-authenticate, I should have noted that.
> 
> I cant say it's been tested long-term but hopefully v1.10.13 should get folks back up and running. A consequence of the change SS made is that we are now at their mercy in terms of how frequent we will have to re-login. It's not clear what they have that set to (30 days — 1 year) but it should mimic the mobile app which anecdotally I don't think logs me out every 30 days.
> 
> For now this is as good as we can do.

Hey @shamoon, thanks again for the quick work, noticed the issue a few days ago, I am smart enough to restart HOOBs, download the updated plugin, restart again, but because I am always on my phone, forgot I needed to unlink and re-link via the HOOBs app on my MAC, 'doh!  Great work, thanks again, I am back up and running!

**Comment by Grote4life** [comment]
prior to and after updating, my homebridge is not showing  "Launch SimpliSafe Login" anywhere in the settings in Config UI X plugin settings. Am I missing something? I swore it used to be there

**Comment by IndySweeney** [comment]
Are any of the other alarm companies (other than the "big boys" who want contracts) any better?   WIth as often as this happens, and the lack of responsiveness from Simpli --- I wonder if it is simply time to change companies.   

Not to highjack this into a "simplysucks" thread -- they have been incredibly ugly to work with in general for the past year....

**Comment by unn** [comment]
@shamoon can you outline what the url should look like beyond the com.SimpliSafe.mobile:// I've been trying to reauth with the url coming from the console in firefox but none of the urls seem to produce a valid login.

**Comment by unn** [comment]
Seems that running the login process via firefox is also non-viable. Chrome produces the correct looking URL in the console and, to answer my own question, the url looks like... `com.simplisafe.mobile://auth.simplisafe.com/ios/com.simplisafe.mobile/callback?code=[46 char string]`

**Comment by phantomsoul1** [comment]
I'm seeing the same issue as unn. Paste in the com.simplisafe.mobile:// URL shown in Chrome's Javascript console and there's no response from the plug-in. No message about the code being successfully extracted, like I would see before; no message about any kind of errors or other failures.

Is it possible that SS has added some new possible characters to these codes that may need to be better escaped, causing an internal error situation in the plug-in that is getting swallowed up and creating an effect like nothing is happening?

**Comment by phantomsoul1** [comment]
When putting logging into debug mode, I can see that the code extraction from the URL is successful, but then Axios shows an ETIMEDOUT message when getting the token (presumably using the extracted code)

`
[02/05/2023, 16:07:34] [Homebridge UI] [homebridge-simplisafe3] Incoming Request: /getAuthCodeFromUrl
[02/05/2023, 16:07:34] [Homebridge UI] [homebridge-simplisafe3] Incoming Request: /getToken
[02/05/2023, 16:07:42] [SimpliSafe] SimpliSafe credentials refresh failed
[02/05/2023, 16:07:42] [SimpliSafe] Recovery credentials refresh failed with error: {
  message: 'connect ETIMEDOUT 2606:4700::6812:e66:443',
  name: 'Error',
  description: undefined,
  number: undefined,
  fileName: undefined,
  lineNumber: undefined,
  columnNumber: undefined,
  stack: 'Error: connect ETIMEDOUT 2606:4700::6812:e66:443\n' +
    '    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function (anonymous)] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      Host: 'auth.simplisafe.com',
      'Auth0-Client': 'eyJ2ZXJzaW9uIjoiMi4zLjIiLCJuYW1lIjoiQXV0aDAuc3dpZnQiLCJlbnYiOnsic3dpZnQiOiI1LngiLCJpT1MiOiIxNi4zIn19',
      'User-Agent': 'axios/0.26.1',
      'Content-Length': 141
    },
    baseURL: 'https://auth.simplisafe.com/oauth',
    method: 'post',
    url: '/token',
    data: '{"grant_type":"refresh_token","client_id":"42aBZ5lYrVW12jfOuu3CQROitwxg9sN5","refresh_token":"LBqWWfaCbjbcr_BeEyrwBj8fkUcSyIjv-CUNQfEpiwH-w"}',
    'axios-retry': { retryCount: 3, lastRequestTime: 1683057929742 }
  },
  code: 'ETIMEDOUT',
  status: null
}
`

**Comment by brainstorm-tech** [comment]
I found with my environment, that I had to completely clear my Chrome cache and cookies before I could get the token URL back from SimpliSafe.  So every time I reauthenticate, I clear out the cache before I log into Homebridge to start the process.

 

Without clearing the cache, it appeared to do nothing (possibly a timeout like the one you are seeing).

-Ed

 

From: George Hyros ***@***.***>
Reply-To: homebridge-simplisafe3/homebridge-simplisafe3 ***@***.***>
Date: Tuesday, May 2, 2023 at 2:21 PM
To: homebridge-simplisafe3/homebridge-simplisafe3 ***@***.***>
Cc: Ed Christians ***@***.***>, Comment ***@***.***>
Subject: Re: [homebridge-simplisafe3/homebridge-simplisafe3] [BUG] Unable to maintain auth with SS as of 4/5/23 (Issue #386)

 

When putting logging into debug mode, I can see that the code extraction from the URL is successful, but then Axios shows an ETIMEDOUT message when getting the token (presumably using the extracted code)

[02/05/2023, 16:07:34] [Homebridge UI] [homebridge-simplisafe3] Incoming Request: /getAuthCodeFromUrl [02/05/2023, 16:07:34] [Homebridge UI] [homebridge-simplisafe3] Incoming Request: /getToken [02/05/2023, 16:07:42] [SimpliSafe] SimpliSafe credentials refresh failed [02/05/2023, 16:07:42] [SimpliSafe] Recovery credentials refresh failed with error: { message: 'connect ETIMEDOUT 2606:4700::6812:e66:443', name: 'Error', description: undefined, number: undefined, fileName: undefined, lineNumber: undefined, columnNumber: undefined, stack: 'Error: connect ETIMEDOUT 2606:4700::6812:e66:443\n' + ' at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)', config: { transitional: { silentJSONParsing: true, forcedJSONParsing: true, clarifyTimeoutError: false }, adapter: [Function: httpAdapter], transformRequest: [ [Function (anonymous)] ], transformResponse: [ [Function: transformResponse] ], timeout: 0, xsrfCookieName: 'XSRF-TOKEN', xsrfHeaderName: 'X-XSRF-TOKEN', maxContentLength: -1, maxBodyLength: -1, validateStatus: [Function: validateStatus], headers: { Accept: 'application/json, text/plain, */*', 'Content-Type': 'application/json', Host: 'auth.simplisafe.com', 'Auth0-Client': 'eyJ2ZXJzaW9uIjoiMi4zLjIiLCJuYW1lIjoiQXV0aDAuc3dpZnQiLCJlbnYiOnsic3dpZnQiOiI1LngiLCJpT1MiOiIxNi4zIn19', 'User-Agent': 'axios/0.26.1', 'Content-Length': 141 }, baseURL: 'https://auth.simplisafe.com/oauth', method: 'post', url: '/token', data: '{"grant_type":"refresh_token","client_id":"42aBZ5lYrVW12jfOuu3CQROitwxg9sN5","refresh_token":"LBqWWfaCbjbcr_BeEyrwBj8fkUcSyIjv-CUNQfEpiwH-w"}', 'axios-retry': { retryCount: 3, lastRequestTime: 1683057929742 } }, code: 'ETIMEDOUT', status: null }
