### ISSUE TITLE
[BUG] New motion sensor not yet supported

### ISSUE THREAD

**Issue by maxtm** [homebridge-simplisafe3/homebridge-simplisafe3#403]
### Description

SimpliSafe recently released a new motion sensor. Homebridge logs show it's recognized by SimpliSafe plugin, but not yet supported.

[27/09/2023, 09:39:31] [Home Alarm] Sensor not (yet) supported: Downstairs
[27/09/2023, 09:39:31] [Home Alarm] {
flags: {offline: false, lowBattery:
false, swingerShutdown: false }, serial: '0263222a', type: 20, name: 'Downstairs',
setting: {
off: 2, home: 2, home2: 0, away: 1, away2: 0, instantTrigger: false, sensitivity: 1
},
status: {}, deviceGroupID: 0
｝

### Expected behavior

Work just like other motion sensors.

### Steps to reproduce

Add new motion sensor to system
Reboot bridge
View logs

### Homebridge logs

```bash
[27/09/2023, 09:39:31] [Home Alarm] Sensor not (yet) supported: Downstairs
[27/09/2023, 09:39:31] [Home Alarm] {
flags: {offline: false, lowBattery:
fal
se, swingerShutdown: false }, serial: '0263222a', type: 20, name: 'Downstairs',
setting: {
off: 2, home: 2, home2: 0, away: 1, away2: 0, instantTrigger: false, sensitivity: 1
},
status: {}, deviceGroupID: 0
｝
```

### Homebridge config.json contents

```json
Not applicable
```

### Plugin version

Latest

### Homebridge version

Latest

### Node.js version

Latest

### Host OS

Raspbian

**Comment by shamoon** [comment]
https://github.com/homebridge-simplisafe3/homebridge-simplisafe3/discussions/392
