### ISSUE TITLE
[BUG] Websocket eventCid for alarm disarm

### ISSUE THREAD

**Issue by tethlah** [homebridge-simplisafe3/homebridge-simplisafe3#409]
### Description

This isn't so much a bug as a difference I found.  I've been adapting this library to use in Node-Red and in my testing I found that on lines 509-514 of src/simplisafe.js you have cid 1400 listed as disarmed with "Master PIN" and 1407 as disarmed with "Remote".

I found that eventCid 1400 actually is disarmed with "Keypad" rather than "Master PIN".  The master pin can be used on either remote or keypad.  If you look at the data coming from 1400 or 1406 (alarm canceled), it differentiates "master pin" from other pins in the "pinName" field.  The zoneCid field seems to coincide with the custom pin used and pinName is the label for that pin.

For example, master pin would output something like (omitting erroneous fields):
```
{
    "eventCid": 1400,
    "zoneCid": "1",
    "sensorType": 1,
    "info": "Alarm Disarmed by Master PIN",
    "pinName": "Master PIN",
},
```
While another pin would output something like:
```
{
    "eventCid": 1400,
    "zoneCid": "3",
    "sensorType": 1,
    "info": "System Disarmed by PIN 3 \"Babysitter\"",
    "pinName": "Babysitter",
},
```

This also applies to the alarm being canceled.  I don't know if it really matters for all intents and purposes.  But in my script I've added logic to differentiate what pin is used on the keypad for reporting purposes.  I don't know if you guys ever noticed this and might want to do the same.

### Expected behavior

Same unless you want to change it.

### Steps to reproduce

Return from websocket.

### Homebridge logs

```bash
none
```

### Homebridge config.json contents

```json
none
```

### Plugin version

recent

### Homebridge version

none

### Node.js version

none

### Host OS

Raspbian

**Comment by shamoon** [comment]
Thank you for the info, functionally for us it doesnt matter, no, we dont output that anywhere and HomeKit doesnt use it

**Comment by tethlah** [comment]
No problem, just figured I would share.  I'm glad I was pointed to you guys, I went from racking my brain a couple days ago on how to get my alarm data into node red independent from home assistant to a fully functional flow.  So I appreciate the leg work you've done :)

**Comment by shamoon** [comment]
Sure thing. Always happy to have more eyes on it. The API has been stable for a while, though I’m waiting for the day they turn it off with no warning… 🫠

Biggest issue has always been auth. We used to have a nice flow but the game of cat-and-mouse seems to have ended with us being forced to manually get a token in a browser. Neither I nor the python dev have found an easier way 🤷

**Comment by tethlah** [comment]
I've never used homebridge so I don't know what you can do with it.  But is it possible to open the login window using the application server and display it in a window within your application, have the user authenticate, and then scrape the code from the location header in the response and feed it back into your application?

**Comment by tethlah** [comment]
You already know the response is going to be a 302 found response, and in the headers there's a location that has the code rather than manually getting it from console when it pipes the failure to the debug window.

**Comment by shamoon** [comment]
Ha, yea I played with that approach a bit, it’s mostly limited by the environment homebridge runs these in, so not sure it’s possible.

maybe I’ll take another run at again some day. Cheers.
